### ISSUE TITLE
npm@5 known issue tracking

### ISSUE THREAD

**Issue by zkat** [npm/npm#16991]
I'm gonna use this issue as a central place for folks to find `npm@5`-specific issues/regressions. It'll also help the CLI team dedupe the various repeats we're getting so we can get a more realistic view of the state of things.

## Fixed

**NOTE**: "Fixed" means a fix has landed in `release-next` and is available in the canary. It might not be in the latest released npm yet. You can install the canary with `npm i -g npmc` and use it with the separate `npmc` binary that gets installed. It won't affect your current npm installation.

* ~Missing dependencies after running `npm install` twice (https://github.com/npm/npm/issues/16839)~
* ~"401 Unauthorized/403 Forbidden" for private registries: `_auth` and toplevel `username`/`password` auth not working (https://github.com/npm/npm/issues/16528)~
* ~Installing subdep as toplevel dep causes unmet deps (https://github.com/npm/npm/issues/16741)~
* ~Deps with strange/broken semver ranges not handled the way they used to be (https://github.com/npm/npm/issues/16744)~
* ~npm drops permissions to `SUDO_UID` for `node_modules` when installing as root (it should only do this for the cache) (https://github.com/npm/npm/issues/16766)~
* ~Mystery issue with `postinstall` scripts and missing directories (https://github.com/npm/npm/issues/16772)~
* ~npm not getting proxy settings from userconfig (https://github.com/npm/npm/issues/16783)~
* ~npm5 ignores `os` field when checking validity of install (https://github.com/npm/npm/issues/16810)~
* ~`Cannot read property 'type' of undefined` coming from `shrinkwrap.js` (https://github.com/npm/npm/issues/16812)~
* ~npm5 fails to install correctly on Docker (https://github.com/npm/npm/issues/16807)~
* ~Spurious `extraneous` packages after a successful install (https://github.com/npm/npm/issues/16820)~
* ~Local binaries fail to get linked sometimes (https://github.com/npm/npm/issues/16837)~
* ~`strict-ssl` and custom CA/cert stuff not working (https://github.com/npm/npm/issues/16868)~
* ~Manual edits to `package.json` ignored (https://github.com/npm/npm/issues/16878)~
* ~npm5 unable to install particular suspicious tarballs (https://github.com/npm/npm/issues/16882)~
* ~The way npm sets user permissions makes Docker unhappy when using `userns-remap` (https://github.com/npm/npm/issues/16892)~
* ~npm uses tarball permissions instead of forcing its own like it used to (https://github.com/npm/npm/issues/16896)~
* ~`npm install` sometimes fails to install some dependencies on a fresh install (https://github.com/npm/npm/issues/16902)~
* ~Other missing dependency corner cases (https://github.com/npm/npm/issues/16944)~
* ~Forwarded git deps not working (https://github.com/npm/npm/issues/16954)~
* ~`npm i --production` modifies `package-lock.json` (https://github.com/npm/npm/issues/16967)~

## Known Issues

* Installing local directory packages that have an `npm-shrinkwrap.json` in them fails (https://github.com/npm/npm/issues/16601)
* `Error: Argument #2 ... but got null` (https://github.com/npm/npm/issues/16665)
* Unable to publish directly from tarballs (`Cannot read property algorithm of undefined`) (https://github.com/npm/npm/issues/16723)
* Running `npm install` on a repo shrinkwrapped with `npm@<5` yields different install (https://github.com/npm/npm/issues/16728)
* Unable to uninstall global packages if installed with `npm@<5` (https://github.com/npm/npm/issues/16738)
* symlinked dependencies get their dependencies manipulated or blown away even when they're not in a subdirectory of the parent (https://github.com/npm/npm/issues/16788)
* `--save-dev` is removing installed deps (https://github.com/npm/npm/issues/16794)
* `npm repo x` fails if `x` is installed in the current dir (https://github.com/npm/npm/issues/16796)
* npm crashes in confusing way if package name is an empty string 
 or if there's no `package.json` (https://github.com/npm/npm/issues/16816)
* Native build scripts running in the wrong order (https://github.com/npm/npm/issues/16824)
* `cb() never called` on `npm outdated` (https://github.com/npm/npm/issues/16825)
* npm reports error but fails to exit if requested version does not exist (https://github.com/npm/npm/issues/16827)
* Spurious argument being added to some lifecycle scripts (https://github.com/npm/npm/issues/16831)
* Attempting to upgrade npm5 yields `EEXIST` errors against previous npm source files, specially of npm was installed through something other than npm (https://github.com/npm/npm/issues/16833)
* `npm unlink` edits `package.json` (https://github.com/npm/npm/issues/16838) (hint: `npm unlink` is just an alias for `npm rm` ;) )
* `npm outdated -g` prints nothing (https://github.com/npm/npm/issues/16840)
* `npm install-test` ignores `package-lock=false` config (https://github.com/npm/npm/issues/16843)
* npm broken after upgrade (https://github.com/npm/npm/issues/16847)
* Somehow, invalid integrity strings can make it into package-lock.json (https://github.com/npm/npm/issues/16861)
* Spurious warning due to `notice` loglevel (https://github.com/npm/npm/issues/16862)
* npm5 tries to install already-installed package that has `private: true` (https://github.com/npm/npm/issues/16883)
* npm5 doesn't treat network timeouts the same (https://github.com/npm/npm/issues/16884)
* globally installing packages without a name seems to make npm uninstall itself (lol) (https://github.com/npm/npm/issues/16891)
* npm does not generate full lockfile unless a full install is run, first (https://github.com/npm/npm/issues/16893)
* `npm update` does not install missing devDeps (https://github.com/npm/npm/issues/16901)
* Some folks seeing `cb() never called!` issues for regular installs, not just global uninstalls (https://github.com/npm/npm/issues/16904)
* npm exits before finishing output when run as a child process for some commands (https://github.com/npm/npm/issues/16932)
* scope registry not working in some cases (probably when installing off tarball URIs) (https://github.com/npm/npm/issues/16933)
* sha1 used on first install, then sha512 (https://github.com/npm/npm/issues/16938)
* npm not checking permissions before upgrading itself (https://github.com/npm/npm/issues/16939)
* `npm install-test` runs tests twice when `package-lock=false` (https://github.com/npm/npm/issues/16940)
* npm gets hosed after upgrade (https://github.com/npm/npm/issues/16947)
* project-local npm removes its own dependencies sometimes (https://github.com/npm/npm/issues/16949)
* npm pretends to successfully remove non-existent global packages (https://github.com/npm/npm/issues/16956)
* Maximum callstack exceeded is back and full of vengeance (https://github.com/npm/npm/issues/16968)
* `npm link` is weird right now (https://github.com/npm/npm/issues/16970)

**Comment by gigafied** [comment]
@zkat https://github.com/npm/npm/issues/16273

**Comment by steebchen** [comment]
Literally everyone I know who tried npm5 or uses node v8 had problems with the lockfile. On my CI environment one of my private modules won't be installed and on my staging servers gulp won't be installed –
 when removing node_modules and npm installing locally (and reading from the lockfile), everything works fine. Same lockfile, same node version (8.0.0) and same npm version (5.0.3). This is really really frustrating, as npm5 ships with node v8. I really love npm and its ecosystem, but I never had more problems than right now.
I won't comment on the classic "Cannot find module 'semver'" issue or that I can't even develop with npm link anymore.
I think I have to manually install npm@4 on all my systems again..

**Comment by zkat** [comment]
@steebchen I don't know why it's broken on Docker. We're looking into it, but that's the main place where `Cannot find module 'semver'` seems to happen. I don't really know if that has anything to do with the package lock, but I doubt it.

npm5 was meant to be a big change. It rewrote a lot of core components of npm that were long overdue for a rewrite. This is what we needed to do in order to bring npm into the future, support the features people kept asking us about, and fix a bunch of old issues that required a rewrite in order to even fix.

And rewrites have a cost that we've always known about: instability. That's a reality of this sort of change, and the CLI team was very concerned about the effects it would have, specially on a tight enough timeline so we could land in node8 and people could take advantage of new features sooner. The conclusion was that a brief period of instability following release was an acceptable cost to pay for the huge benefits, both now and in the near future from features that are now possible. node8 has its own bugs, and it'll continue to stabilize.

I think it's generally good practice to stay away from bleeding edge releases if you can't handle breakage. This applies to all software, ever. The CLI team, all two of us, are working hard to get npm5 to a better place and there's already huge swaths of our userbase greatly benefitting from the tool _right now_. We're not gonna take that away. I recommend that if you find an issue and you can't work around it or you expect things to "just work" like they used to, you go ahead and revert to npm@4 until you have more confidence that npm5 will serve your needs smoothly. I don't think this is necessary for the majority of our users, but the userbase of npm is such that even a small % of users being affected by an issue turns into tens of thousands of people very quickly. That's just how that cookie crumbles.

Please do report stuff! We're working hard at this, and fixes go very quickly into our new canary. We've also got a faster release cadence. Note that a lot of the issues in the OP here have already been fixed, but I've been too busy triaging and fixing issues to comb through them and cross out the ones that already work. 👍 

Cheers!

**Comment by mmc41** [comment]
@zkat Actually, "Cannot find module 'semver'" also happened for me after upgrading from npm 4 to 5 on Mac OS X (no Docker). Had to delete various npm folders to workaround it if I recall correctly.

**Comment by Priyansh** [comment]
Hello Folks,

I'm trying to install React Native through CLI command in Window OS, and I have npm version 5.0.3 and it is not supported yet for using React native. Any idea how to fix below bug : Is there any possible way to change npm version from 5 to 4 in order work on React Native?

 Thanks in Advance
*******************************************************************************
ERROR: npm 5 is not supported yet
*******************************************************************************

It looks like you're using npm 5 which was recently released.

Create React Native App doesn't work with npm 5 yet, unfortunately. We
recommend using npm 4 or yarn until some bugs are resolved.

You can follow the known issues with npm 5 at:
https://github.com/npm/npm/issues/16991

*******************************************************************************

**Comment by steebchen** [comment]
@Priyansh `npm i npm@4 -g` to use npm 4

**Comment by steebchen** [comment]
@mmc41 @zkat I don't use docker either so yeah it has nothing to do with that I suppose. I upgraded using Linux, got this error and I had to manually remove some folders too (not complaining, just providing information).

**Comment by kachkaev** [comment]
Also have an issue with npm5 inside GitLab CI. All works ok when there is no cache between the builds and so npm installs everything from scratch. When I enable cache like this:

```diff
# .gitlab-ci.yml
image: node:8

stages:
  - qa

qa:
  stage: qa
+  cache:
+    paths:
+      - node_modules
  script:
    - npm install
    - npm run test
```

here is what happens:

1. First build runs OK
2. Any consequent builds with exact the same `package-lock.json` also run OK and they are superquick (yay!)
3. Any minor change in `package-lock.json` creates this in the logs:

```
npm install

npm info lifecycle color-convert@1.9.0~preuninstall: color-convert@1.9.0
npm info lifecycle color-convert@1.9.0~uninstall: color-convert@1.9.0
npm info lifecycle color-convert@1.9.0~postuninstall: color-convert@1.9.0
# many more uninstall lifecycle events
# ...
# no re-install attempts for color-convert and other modules that were deleted
# despite still being in package-lock.json
# ...
removed 29 packages and updated 189 packages in 21.445s
npm info ok 

npm run test
# ...
Error: Cannot find module 'color-convert'
    at Function.Module._resolveFilename (module.js:485:15)
```

It feels like too many modules are uninstalled and not installed back again while npm tries to sync the contents of `node_modules` with the latest `package-lock.json`

Using node 8.1.0 / npm 5.0.3 (docker node:8). Hope this helps!

**Comment by ljharb** [comment]
Also #17269, which may be related to #16904.

**Comment by Alhadis** [comment]
> support the features people kept asking us about

If perchance one of those features was a _"leave my `package.json` file's damn indentation alone"_ request, well, congratulations! You're almost there. Seeing the file reformatted with tabs is a refreshing change, but I'd much prefer it **not being reformatted at all**.

It's pretty absurd for a package manager to be enforcing "consistent formatting" when we already have countless style-checkers, linters, and code reformatting tools whose **sole purpose** is handling this sort of ancillary taskwork.

Even ostensibly helpful stuff [like this](https://github.com/npm/npm/blob/7b9b568/lib/install/update-package-json.js#L42-L45) is making a blind assumption the user hasn't organised a keyword list by topic, or some other indiscernible/personal criteria running counter to alphabetical order.

**Comment by yyjdelete** [comment]
#17267 Another issue may lead to some `Cannot find module` issues.

**Comment by ben-page** [comment]
That list is massive. And I can't believe that some of this stuff wasn't caught by unit tests. Basic stuff like `npm -g outdated` and `npm -g r package` are not working. And the `cannot find module` issues make npm 5 unusable in many cases. These are not edge cases. Basic functionality is totally broken. Frankly, this would be a bad RC, let alone a stable release. I can't understand why was shipped with node 8.

Please, you should update npm 4 for node 8 and revert to bundling npm 4 for a while.

**Comment by naholyr** [comment]
:+1: for *not* bundling a heavily bugged package manager in a LTS version of Node :/ This was a huge mistake for production users. But I think it's node-related more than npm-related, so → nodejs/node#13815

It would give more time to npm team to work around those issues painlessly. I hope such decision will be made for the sake of users, and for npm developers to decrease the pressure ;) Be sure we're grateful for all the work accomplished here!

**Comment by gaearon** [comment]
>I think it's generally good practice to stay away from bleeding edge releases if you can't handle breakage. 

As a tool maintainer, the problem for me is that `npm@5` is what people get when they download "Current" release on https://nodejs.org with "Latest Features":

<img width="307" alt="screen shot 2017-06-23 at 5 23 16 pm" src="https://user-images.githubusercontent.com/810438/27491044-aad14826-5838-11e7-98e9-d7e89ade7a60.png">

There is no wording there to suggest that Node 8 is unstable, or that it ships with a package manager that is bleeding edge.

I understand there are good reasons for shipping it, and that you can't influence Node.js website wording, but as a result beginners suffer.

For example, errors in https://github.com/facebookincubator/create-react-app/issues/2558 are inscrutable to anyone who doesn't have experience with debugging npm, but it happens today for every Windows user of webpack.

We could add a check in Create React App itself, and refuse to run on `npm@5`, but I'm worried this will be hostile. 😞

I'm curious what would be a better way to handle this in the transitionary period.

**Comment by brentvatne** [comment]
> We could add a check in Create React App itself, and refuse to run on npm@5, but I'm worried this will seem hostile. 😞 I'm curious what would be a better way to handle this in the transitionary period.

I would also like some advice on this. Currently we actually have this check in Create React Native App because too many users were running into problems. It is very confusing for beginners to install the latest version of Node to try out a project, then learn that the default version of the package manager included with Node is not stable and be forced to downgrade.

**Comment by gaearon** [comment]
Anyway—I'm sorry for hijacking the thread. I now realize this issue might not be the best place to discuss this kind of meta concern. Let's keep this thread focused on known issues, and if there is interest, maybe we can discuss about the meta concern (what is best approach for tools relying on npm) in some other place.

**Comment by zkat** [comment]
I'm on vacation for a few more days (and have been for ~1.5 weeks) and Rebecca's been sick. We'll get back to y'all and I can only assume you'll see things getting fixed much faster once the whole team is back to full speed. Cheers!

**Comment by gaearon** [comment]
Sounds great! Thanks for your work on this release. ❤️

**Comment by Jokero** [comment]
You published npm5 too early. It's totally unusable :smile:

**Comment by snewell92** [comment]
## About the linked rollup issue

### Error I was getting
<details>
<summary>OG error</summary>

When running an npm script with `rollup -c rollup-config.js` I got the error:

```
🚨   Cannot find module 'magic-string'
```

where magic-string is a dep of rollup, and then after `npm install`ing magic-string:

```
The final argument to magicString.overwrite(...) should be an options object.
  See https://github.com/rich-harris/magic-string
```

which does not happen when rollup is installed correctly.
</details>

### Detailed information / Description

<details>
<summary>info</summary>

For more info on the linked rollup issue, I had initially installed rollup in the context of a fullstack app with angular in the front end, so I was using rollup to get tree-shaking and browser-friendly bundles of my angular code - got that all to work, but then I moved some things around and it borked.

I believe I ran `npm install magic-string` to test something, then `npm uninstall magic-string` which probably removed magic string altogether even though `rollup` is still referencing it. Might be an overeager npm uninstall...? Idk, maybe I just ran `rm -rf node_modules && npm install && npm run build` and that got into the weird state. Unsure...

After uninstall magic-string (my app code doesn't use it, it's just a dep of rollup), I just ran `npm uninstall` on all my rollup packages, then `npm install`'ed them all again and it solved my problem on my local windows machine.

Side note... The real issue is my CI machine's cache got borked, so I'll have to try and wrangle with that guy.

Back on my local windows machine, running `rm -rf node_modules && npm install && npm run build` (that last npm script runs the rollup command, so it would test if npm installed everything).... This works - so, **my suspicion is that `npm uninstall` removed the magic-string entry in `package-lock.json` which informs npm, in some cases, to remove packages that may still be referenced in the deps of still referenced packages**. Could be a problem with how things are deduped, or just a bug in uninstall, or something. 🤷‍♂️  Good luck with that one! xD (hopefully just a user error and y'all don't have to sweat it xD).

Future reference - I couldn't repro the issue in a simpler repo with just plain javascript files and a plugin-less rollup. :\ Not sure if I should spend time trying to repro either (as I got my app to build right) - Hopefully it was just a weird one off that I dug myself into...

Hopefully that gives y'all some direction with the linked rollup issue.
</details>

------

#### Complaint about node-gyp (unrelated)
<details>
<summary>unrelated aside about npm / node-gyp</summary>

Npm always rebuilds node-sass any time I nuke my node_modules and run npm install, shouldn't node-gyp globally/per-user cache those builds? Or does it only do it locally? I'd rather not have to globally install node-sass... but if that's the only way... **it made debugging this issue a pain since node-sass rebuilt all the time**. Even though I don't want to globally install node-sass, I'd be fine with npm/node-gyp caching a local install of a native binding to my user's app data or wherever npm decides to put it. $.02 - luckily this machine has visual studio / c++ tools so it can compile that stuff fine.

For now i just ran `npm i -g node-sass` and I got a binary to be globally cached... woooooooo.

</details>

**Comment by jakeNiemiec** [comment]
>Npm always rebuilds node-sass any time I nuke my node_modules and run npm install, shouldn't node-gyp globally/per-user cache those builds?

@snewell92 This happened to me, see below 👇 from this issue: https://github.com/npm/npm/issues/16866 ...**just removing `node_modules` seems to (sometimes) cause nasty side-effects.**

> For a clean install: `npm cache clean --force && rm -rf node_modules && rm -f package-lock.json && npm install`

**Comment by jaggs6** [comment]
can we add this to the above list please. https://github.com/npm/npm/issues/17141

**Comment by zkat** [comment]
Update: A *bunch* of these known issues are fixed already and will be included in next week's release. I'll go through this on Monday or something and strike out everything that's already fixed, but all the relevant issues should have been closed by now.

**Comment by zkat** [comment]
Another update: I went through and moved everything in here that already has a fix landed at least in canary. We've a few more coming today, and @iarna and I might be rolling a new release today, instead of Wednesday. ^_^;;

And, well, other critical issues will continue to be prioritised, and fixing critical issues continues to take priority over putzing around on the issue tracker. I know it's less than ideal to get radio silence for a bit, and I'm trying to help keep that under control, but the reality is I'd much rather be making npm actually work, rather than telling y'all we're working on it, and our two-person team is pretty time-constrained. ^_^;;

**Comment by medikoo** [comment]
@zkat can you add #16907 ? It was closed  by bot, I'm not able to reopen it.

Still issue is valid, and we're unable to use npm@5 in our projects cause of that.

**Comment by ghost** [comment]
@zkat 

> Please do report stuff!

Not clear from above^ whether this is already dealt with ...

With a clean tarball install of 

```
node -v && npm -v
    v8.1.3
    5.2.0
```

which *does* install
```
semver@5.3.0
```

fails, on exec, to find 'semver'
```
Error: Cannot find module 'semver'
```

details here:

https://pastebin.com/raw/6WtGYNhH

fwiw, dropping back to 
```
node -v && npm -v
	v8.1.3
	4.0.5
```

doesn't seem to fix
```
node /tmp/test.js
module.js:487
    throw err;
    ^

Error: Cannot find module 'semver'
```

and,
```
npm ...#canary
npm ...#release-next
```

both exhibit the same issue. here, anyway.

**Comment by NasCorp** [comment]
There is no commits for almost 2 weeks... Anyone fixing **npm 5** problems? Do you want to make developers **hate** Node.js at all? :eggplant: :-1:

**Comment by Alhadis** [comment]
> Do you want to make developers **hate** Node.js at all? 🍆 👎
>
> 🍆

... what the hell does an eggplant have to do with any of this...

**Comment by snewell92** [comment]
[There have been commits](https://github.com/npm/npm/commits/release-next). Don't just look at the latest branch and canary branch, work is going on daily on local branches, and different remote branches, before they merge those changes into canary / latest (which would trigger a release, I assume).

They're working hard and are going to cut another release as soon as they are able.

**Comment by NasCorp** [comment]
Sorry, there is really 5 commits from 14'th of July. And no one of them is bugfix - only improvements. 
:eggplant: :-1:

**Comment by jakeNiemiec** [comment]
> Anyone fixing npm 5 problems? Do you want to make developers hate Node.js at all? ~~🍆 👎~~

@NickolasSh **This is the price of open source.** Being a project maintainer is a thankless job (thanks @zkat, @iarna & others 👍 ). 

[Check out the pulse page for a better idea of current activity](https://github.com/npm/npm/pulse/monthly).

**Comment by Alhadis** [comment]
@NickolasSh Quit whining, unless you're paying the developers to meet a certain deadline. We get that it's frustrating, but holy crap, you are seriously not gonna win friends or influence people by throwing shit at the developers as thanks for their continued hard work.

Keep it up guys, and ignore this whiny little shit. We know shit will get fixed eventually. =) 👍 

**EDIT:** loooooool, NikolasSh 👍 d his own comments after they copped 5 👎 reactions.

<img src="https://www.organicfacts.net/wp-content/uploads/2013/06/Eggplant-1020x765.jpg" width="300" alt="Irrelevant vegetable" />

**Comment by NasCorp** [comment]
@jakeNiemiec, thats what I found on [npm page](https://www.npmjs.com/jobs) 

> npm, Inc. maintains the npm package manager for JavaScript and hosts the world’s largest software registry. 

> We offer very competitive salaries, meaningful equity, and generous health, dental, and vision benefits. We love it when you represent us at conferences.

As I understand @zkat and @iarna working in npm inc. and getting salary for maintaining npm.
[And take a look at weekly activity](https://github.com/npm/npm/pulse) :-1: 

@Alhadis, I just want to be sure that the developers understand the scale of the problem.
PS, Of course I :+1: d my own comments, and another plus I asked to put my friend. :eggplant:

**Comment by ljharb** [comment]
@NickolasSh there's plenty of work done in an engineering job that isn't "writing code", and not all of npm's code is public - but regardless, it's not for you to judge how well someone is earning their salary, since you're not their employer. Your comments and emoji choices are inappropriate, and the amazingly talented and hardworking npm developers don't deserve to be maligned just because things aren't proceeding the way you personally think they should be.

**Comment by jrop** [comment]
@zkat @iarna @ljharb there are tons of people who are benefiting from your work.  Keep it up!  You guys have your plates full and are doing an amazing job.

@NickolasSh dude you gotta chill!  The beauty of open source is that anybody can contribute.  However, right now all you are contributing is negative energy.  Nobody likes a [taskmaster](https://www.google.com/search?q=define+taskmaster).

**Comment by BaktybekNurbakyt** [comment]
**npm install -g npm@latest-4** WORK WORK WORK WORK

**Comment by jakeNiemiec** [comment]
@BaktybekNurbakyt Don't expect any support:

>The npm CLI project does not have designated LTS releases. The project only regularly does releases to the most recent major release.

>These older versions of npm will continue to work with the registry.npmjs.org registry but may not support all of its latest features.

http://blog.npmjs.org/post/162451604515/the-npm-clis-long-term-support-lts-policy

**Comment by webmobiles** [comment]
please give a solution that works with nodenv? i need install node 7, or node 8.. ?

**Comment by uniphil** [comment]
Looks like some more of these known issues have been fixed! :tada: :steam_locomotive: 

https://github.com/npm/npm/issues/16738
https://github.com/npm/npm/issues/16847
https://github.com/npm/npm/issues/16861
https://github.com/npm/npm/issues/16891

**Comment by kanika46shah** [comment]
Adding one more issue in the list of issued that need to be fixed https://github.com/npm/npm/issues/18352

**Comment by n3dst4** [comment]
Can I suggest that #18380 should also be added? That one's actually a regression in 5.4.0 as compared to 5.3.0 so not sure if it counts for this page.

**Comment by Mardoxx** [comment]
@NickolasSh bit unfair to say they don't contrib enough, one of them submitted a change that broke npm install in npm 5.4!

**Comment by iosdev-republicofapps** [comment]
npm@5 seems to totally break react native.  Can't even use `create-react-native-app`.  Yarn doesn't seem to work with nvm.  I checked https://github.com/facebook/react-native/issues/14767 but no help there ... Any ideas?  :-)  I'd be happy to help but I have no idea where to start.  Could somebody give me a suggestion?

**Comment by iosdev-republicofapps** [comment]
I have react native running with npm 4.6.1, but as newcomer to both node and react native, it makes me a bit nervous to have to depend on a version of npm that's many versions behind the current stable version of npm.  But it is working ... Let me know if I can help!  :-)  BTW, thanks for all you do making npm available for free - not meaning to be a whiner, just frustrated, that's all.

**Comment by mgol** [comment]
> Yarn doesn't seem to work with nvm.

What do you mean? I'm using Yarn with nvm without problems, same for a few of my colleagues.

**Comment by zkat** [comment]
I'm gonna close this 'cause I really can't maintain this, which involves repeatedly going back and re-testing everything after every release. Managing incoming issues is hard enough as-is, and this was meant to be a temporary thing during the initial issue burst.

We're gonna keep working on fixing issues: if y'all feel like things have been slow, it's largely because it's conference season and the team's been getting dragged around to different engagements. Things should start chugging along soon again after that. :)

**Comment by Mardoxx** [comment]
Raises the question, why the hell push several releases (broken releases
should I say) when no one is around to fix potential issues.... lol.

**Comment by luislobo** [comment]
@mardoxx no one forces anyone to update. Eveyone has options: keep using the version that works for you, update to the latest and see if it works. Oh, and even fix the bugs you find!

**Comment by mmc41** [comment]
@luislobo Everyone has options ... but npm 5 comes along with the newest version of node when it is installed and beginners may not know how to update. I installed promptly downgraded when I found out the hard way that npm 5 was broken but I imagine that many newbies will give up or draw incorrect conclusions about the quality of the entire platform. So it is a bigger issue than just "shut up and fix the bugs" to the people that complain.

**Comment by medikoo** [comment]
True, biggest issue is that npm@5 was unfortunately bundled with node@8.

Still that's a bug on Node.js side. The good news is that lesson was learned, and it should not happen again. More care will be taken with next Node major releases. See: https://github.com/nodejs/node/issues/13815

**Comment by luislobo** [comment]
@mmc41 I agree about it for new people. But, for experienced ones, I don't. It's pretty common having npm packages that does break stuff. That's one of the reasons why, in our production code, not a single package uses wildcards in version numbers. Been there too many times, with packages breaking a stable release, just because a new instance had to do `npm install` and a dependency dependency broke everything.
Anyway, I agree that things can be better tested. May be that can be improved. I just don't like coming here and blaming people, just like that, without taking action, and being at the same time rude or in a harsh language demanding it, just like if people owed any other the right to have stable and bugless code. This is Open Source. These things happen, the only way to fix it is get more people involved in coding, testing, etc.

**Comment by zkat** [comment]
I'm gonna lock this 'cause I keep getting pinged and I can't imagine this conversation going anywhere good the way it's happening.

Again: we're working on the fixes. I'm just not using this issue to track it anymore because it is not an effective medium for it. We're collecting blockers in other ways and prioritizing what we'll be fixing in the next couple of weeks/months according to that.

We're also working on new stuff, which is needed in order to help stabilize stuff -- npm is in a bit of an interim state while we move to this new model, and we're rewriting and refactoring a lot of its core. This will help us make npm more maintainable/testable/patchable, and ultimately more stable. But while all that stuff lands, we're going to have all this very fresh code, and we're going to be finding a lot of corner cases our very large community had grown used to -- and we'll have solutions for those.

My suggestion for folks is that if you can't upgrade: wait for it. npm@5 is a massive shift from older version and introduces a ton of new things and workflows. The CLI team decided to release npm5 when we did because it worked for us and for a number of people -- and the positive changes with npm5 are huge enough that there's a lot of people willing to use the bleeding edge and who have had a great experience with it. The work now is to extend those benefits to the rest of y'all <3.
