### ISSUE TITLE
getting "Cannot find module 'internal/fs'" in Node.js v7.0.0

### ISSUE THREAD

**Issue by Gcaufy** [npm/npm#14232]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?

When I use node v6.7.0, I do `npm install`, it works well.
After I upgrade to v7.0.0-nightly, I get an error:
```
Cannot find module 'internal/fs'
```
Then I downgrade to v6.7.0, it works well again.

#### Errors
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\installed\\nodejs\\node.exe" "D:\\installed\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "express-generator"
npm ERR! node v7.0.0-nightly201609202b5acda7a2
npm ERR! npm  v3.10.3
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\code\mine\js\success_with_social\npm-debug.log
```

### Detail
```
$ node -v
v7.0.0-nightly201609202b5acda7a2
$ npm -v
3.10.3
$ npm install -g something
##### Geting error here

##### Then I downgrade to v6.7.0
$ node -v
v6.7.0
$ npm -v
3.10.3
$ npm install -g something
(node:72796) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
C:\Users\changong\AppData\Roaming\npm
`-- something@0.0.1
```

### Other
I also checked this issue [#12880](https://github.com/atom/atom/issues/12880)
But I tried to uninstall and install many times, it does not work for me.

I download Node.js from these two links:
[V6.7.0](https://nodejs.org/dist/v6.7.0/node-v6.7.0-x64.msi)
[v7.0.0](https://nodejs.org/download/nightly/v7.0.0-nightly201609202b5acda7a2/)

**Comment by othiym23** [comment]
You're going to need to upgrade to `npm@3.10.9` (currently `npm@next` – `npm -g install npm@next` if you have it installed globally, [`npm-windows-upgrade`](https://www.npmjs.com/package/npm-windows-upgrade) to make it easier on Windows), because there's a backwards-incompatible change made to Node's internals that require a newer version of `graceful-fs`, a utility package heavily used by the npm CLI. Thanks for your time!

**Comment by othiym23** [comment]
Also, you should be able to use the version of npm packaged with Node 7.0.0, but you may need to manually delete any copies of npm that don't get uninstalled by Node's uninstall script.

**Comment by Gcaufy** [comment]
cool, works for me.

**Comment by piotr-cz** [comment]
If this happens when running **gulp**, you have to downgrade nodejs to v6, see https://github.com/gulpjs/gulp/issues/1843

**Comment by tim-mc** [comment]
This error is also happening for me with node 7, npm versions 3.10.9 & 4.0.1. Should I open a separate issue?

**Comment by jackiehluo** [comment]
Same as @tim-mc!

**Comment by hult** [comment]
Had the same issue as @tim-mc @jackiehluo, tried different versions of npm (including the one packaged with node), but it didn't help. Removing my `node_modules` and reinstalling all packages worked splendidly, though.

**Comment by piotr-cz** [comment]
Check error stack trace, there is a change that there is a dependency _vinyl-fs: 0.3.0_ which is causing this

**Comment by heziqiang99** [comment]
@othiym23 it works, thanks!

**Comment by ymc-sise** [comment]
Same as @tim-mc!

**Comment by tim-mc** [comment]
FWIW, I've tried removing `node_modules` and rebuilding. It does not solve the issue.

**Comment by joelself** [comment]
I can't upgrade npm because I get the same `Cannot find module 'internal/fs'` error when I try to upgrade:

```bash
username@machine:~/$  npm install npm@3.10.9
npm ERR! Linux 3.13.0-91-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "npm@3.10.9"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by guyellis** [comment]
@joelself I found that to get around that problem I had to:
1. Switch Node from 7.0.0 back to 6.x
2. Then run ` npm -g install npm@next` (or whatever version you want)
3. Then switch back to Node 7.0.0

**Comment by vuongtran** [comment]
@guyellis It work fine for me. Thanks!

**Comment by juankmarin** [comment]
Works for me removing the node_modules folder and install again

**Comment by gempain** [comment]
@guyellis completing your comment:
Use command `n` to switch between NodeJS versions.

**Comment by guyellis** [comment]
@gempain thanks. I should have mentioned that `n` and `nvm` are node version managers. Not sure if there are others?

**Comment by gempain** [comment]
@guyellis not sure either. But I think your comment pas perfect as is. I guess I should've known how to switch node version. But the Google search took me a minute, so not too bad :)

**Comment by one-aalam** [comment]
@guyellis Thanks! worked like a charm

**Comment by thedillonb** [comment]
This doesn't appear to be fixed in 3.10.9 as suggested above. Pulling the latest NodeJS current release (7.2.0) which bundles NPM 3.10.9 still results in failure:

```
[dbuchanan@localhost server (normal-work)]$ npm --version
3.10.9
[dbuchanan@localhost server (normal-work)]$ npm test
module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/code/i95/web/server/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[dbuchanan@localhost server (normal-work)]$
```

**Comment by xpolb01** [comment]
I had the same issue. What I did was the following: 

1) using "n" I  switched back to the node version 6.9.1 `n 6.9.1`
2) installed lates npm   `sudo npm -g install npm@next`
3) switch back to node 7.2.0 `n 7.2.0`
4) everything works

**Comment by bountyx** [comment]
@guyellis Same issue, your instructions also worked for me. Can anyone shed light onto WHY that fixes the issue?

**Comment by lsommaruga** [comment]
@xpolb01  Thnks also work for me OS X Yosemite 10.10.5 (got the error while installing nodemon module  _npm install -g nodemon_ )

**Comment by tim-mc** [comment]
Resolved my issue - Bower was the culprit. We had some legacy code in our codebase that still depended on it.

**Comment by willybc** [comment]
error , i have version 3.10.9 
i change version , no work 
`module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (C:\Users\UsuarioPC\Desktop\platzigram\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)`

**Comment by nfantone** [comment]
npm `4.0.3` still shows this issue on macOS Sierra. @othiym23 It should really be reopened (or is it being tracked somewhere else?).

**Comment by through-a-haze** [comment]
`node -v` v7.2.0
`npm -v` 4.0.5
still got this issue

**Comment by olleolleolle** [comment]
_Today's workaround_: I came back after a long time to the code, switch to 6.x, and removed the `npm-shrinkwrap.json` file that pinned some dependencies to non-existent versions.

**Comment by steptobe** [comment]
node -v v7.2.0
npm -v 3.10.9
still got this issue

**Comment by mitchallen** [comment]
This worked for me on a Mac: 

$ sudo n 6.9.1
$ sudo npm -g install npm@next
$ sudo n stable

$ node -v
v7.2.1
$ npm -v
3.10.10

**Comment by medifle** [comment]
@mitchallen 
Works for me! I use `n` manager, too.
It's weird I need to upgrade npm to @next(that is 4.0.5 for now) before installing the latest node version, or npm breaks and say `Cannot find module 'internal/fs'`

**Comment by tsgx1990** [comment]
@mitchallen You are right, thank you!

**Comment by jessaustin** [comment]
Still happened with `npm: '3.10.10', node: '7.2.1'`. Rolling back to `node: '6.9.1'` enabled the `npm` update (well, modulo a warning about `graceful-fs` that didn't cause any immediate problems), but after rolling forward to `node: '7.2.1'` I had to update again to catch up. Hopefully I won't have to do this again, but [tj/n](//www.npmjs.com/package/n) already paid for itself!

**Comment by samanmohamadi** [comment]
Same issue here.
```
]$ uname -r  && node -v && npm -v
4.8.11-1-ARCH
v7.3.0
4.0.5

```

**Comment by felixyin** [comment]
➜  LRS_GAME uname -r  && node -v && npm -v
16.3.0
v7.3.0
4.1.1

**Comment by nfantone** [comment]
Would be nice to reopen this, by now.

**Comment by pstonier** [comment]
I was able to resolve this by installing a few modules globally and wiping and reinstalling my project's `node_modules` folder.

```
npm install -g npm@next
npm install -g node-gyp
npm install -g nodemon

**Comment by keeprock** [comment]
Got a same problem but with Bower. Solved by switching to Node v7.0.0

**Comment by mort3za** [comment]
I had this issue when running gulp.
```
rm -rf ./node_modules
npm install
```
Fixed my issue.

**Comment by app-sparkler** [comment]
**reinstalling** `node_modules` worked for me.  

To be safe, I did not delete the `node_modules` folder, instead just _renamed_ it.

Good Luck.

**Comment by totallytotallyamazing** [comment]
This `npm uninstall -g generator-karma` and this `npm install -g generator-karma`
and then
this `npm uninstall -g bower` and this `npm install -g bower`
All that worked for me.

**Comment by ryx** [comment]
Had the same issue and updating the global module library using `npm update -g` was the only way to solve it for me. Re-fetching local deps, updating shrinkwrap, etc. had no effect.

**Comment by wal-nadeem** [comment]
@ryx Thats worked for me as well!!

**Comment by FunkeDope** [comment]
Issue for me as well. I can't even install anything with ```-g```

```
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm@next"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
```

**Comment by nhhockeyplayer** [comment]
same issue

latest node version

node 7.4.0
npm 3.5.3

cant install or uninstall anything with -g

this is blocking everything

i cannot instrument npm for uninstall or install nor @next

**Comment by nhhockeyplayer** [comment]
npm update -g 

fails refuses to resolve

**Comment by RusAlex** [comment]
node v7.4.0
npm v4.1.1
Fedora 24
nodesource repo

**Comment by RobDong** [comment]
node v7.4.0
npm v4.2
same issue. 

removing node_modules didn't solve. 
only going back to node v6.9.4 helped

**Comment by vitalygoji** [comment]
Yesterday (february 11 20017) upgraded and now  "cannot find internal/js"
npm is a immature piece of shit. gong back to manual. fuck npm

**Comment by nfantone** [comment]
@vitalygoji Wow, there. Easy on the language, fella. I can understand your frustration, but your words have absolutely no place in here (nor everywhere else, to be frank). 

(Also, you got the date wrong: **20017** is yet to come).

**Comment by through-a-haze** [comment]
@nfantone he came from the future and even there it still doesn't work!

**Comment by nhhockeyplayer** [comment]
This issue continues to be a problem
Who is driving the ship ? ???
Microsoft intervened to separate the men from the boys and bailed this company out for the unusable javascript.
Do we need another bailout here ?
I have seen countless sub systems stagger to 75% of the way and then halt only to be bailed out by a higher veteran authority with proper field experience. And mile long threads for debilitating issues that are not solved but continue to hamper and prevent diamond grade engineers from focusing on pure business logic.

Any attempt to install the latest and greatest node.js is NOT properly installing NPM. Its just not happening. My npm --version says 3.6.3 after I installed node.js 7.0

Is there a workaround ? Is there an inherent design problem ?

Sorry I dont want to spend all my time wrestling with installation issues let alone months of already attempted open source sub systems that end up eventually being honked.

what the heck is going on ?

**Comment by nfantone** [comment]
@nhhockeyplayer I just did a `brew install node`, and got:

```sh
→ node -v
v7.5.0

→ npm -v
4.1.2
```

What exactly is your issue, again?

**Comment by nhhockeyplayer** [comment]
C:\apache-tomcat-8.0.23\webapps\ROOT\widgets\client>npm install
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\owner\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.5
npm ERR! npm  v4.3.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: angular-cli@1.0.0-beta.31
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.0.0, 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26, 0.0.27, 0.0.28, 0.0.29, 0.0.30, 0.0.31, 0.0.33, 0.0.34, 0.0.37, 0.0.39, 0.1.0, 1.0.0-beta.0, 1.0.0-beta.1, 1.0.0-beta.2-mobile, 1.0.0-beta.2-mobile.1, 1.0.0-beta.2-mobile.2, 1.0.0-beta.2-mobile.3, 1.0.0-beta.2-mobile.4, 1.0.0-beta.4, 1.0.0-beta.5, 1.0.0-beta.6, 1.0.0-beta.8, 1.0.0-beta.9, 1.0.0-beta.10, 1.0.0-beta.11-webpack, 1.0.0-beta.11-webpack.2, 1.0.0-beta.11-webpack.3, 1.0.0-beta.11-webpack.4, 1.0.0-beta.11-webpack.5, 1.0.0-beta.11-webpack.6, 1.0.0-beta.11-webpack.7, 1.0.0-beta.11-webpack.8, 1.0.0-beta.11-webpack.9, 1.0.0-beta.11-webpack.9-1, 1.0.0-beta.11-webpack.9-2, 1.0.0-beta.11-webpack.9-3, 1.0.0-beta.11-webpack.9-4, 1.0.0-beta.12, 1.0.0-beta.12-1, 1.0.0-beta.14, 1.0.0-beta.15, 1.0.0-beta.16, 1.0.0-beta.17, 1.0.0-beta.18, 1.0.0-beta.19-3, 1.0.0-beta.20-1, 1.0.0-beta.20-2, 1.0.0-beta.20-3, 1.0.0-beta.20-4, 1.0.0-beta.21, 1.0.0-beta.22, 1.0.0-beta.22-1, 1.0.0-beta.24, 1.0.0-beta.25, 1.0.0-beta.25.2, 1.0.0-beta.25.3, 1.0.0-beta.25.4, 1.0.0-beta.25.5, 1.0.0-beta.26, 1.0.0-beta.27, 1.0.0-beta.28, 1.0.0-beta.28.2, 1.0.0-beta.28.3
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'widgets'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\owner\AppData\Roaming\npm-cache\_logs\2017-02-13T22_59_51_855Z-debug.log

C:\apache-tomcat-8.0.23\webapps\ROOT\widgets\client>

**Comment by nhhockeyplayer** [comment]
ok so thats the new one it led me to

so I will upgrade to node-7
and see

**Comment by nhhockeyplayer** [comment]
Vitaly clean up your language your giving the great italians a bad name
if you cant control you english move to england where you will be welcome

**Comment by vitalygoji** [comment]
Dude, some of us live in a REAL world. If you can't fix several years old
bug may be you should consider changing your career . Anyway, thank you for
at least not corrupting my hard drive.
P.S. please educate yourself on usage of a try catch block. See, try catch
block can be used for more than displaying ugly  "we can't find our own
stuff" message. Refer to a good resource on how to gracefully resolve
missing resources issues .
No need to thank me.

**Comment by vitalygoji** [comment]
You are right baby, if it is still there after a few years chances are that
it will be there forever...

**Comment by vitalygoji** [comment]
I tried to install Polymer component with bower, got complaint that I need
to upgrade. Upgraded everything I could (node, npm etc.) and after that
spent entire evening removing cache, reinstalling, installing etc... just
to see that error popping up again and again. Ended up installing Polymer
manually.
Good news is that my Linux is still booting and no viruses asking me to
improve my sex life showing up so far after that experience. Thank you for
not infecting my machine! I need to be more careful downloading
questionable programs off the internet.

**Comment by vitalygoji** [comment]
Language? What language do you think you will be using working on your
future fast food jobs after you boss realises that you can't fix a bug
which was sitting there for several YEARS?

**Comment by mitchallen** [comment]
Fortunately GitHub provides a mute-this-thread option ...

**Comment by vitalygoji** [comment]
That will fix that bug. Thank you!

**Comment by fabrikate** [comment]
I am getting this same issue. 
Node: v7.4.0
 NPM: 4.0.5

Anytime I try and npm install I get the following error: 
`npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/name/frontend/npm-debug.log
`

Any suggestions since I am unable to npm install anything?

**Comment by vitalygoji** [comment]
My advice is to avoid npm. I reported this issue and all I got was a bunch
of insults in return. I am surprised that Google Polymer recommends npm.
We need to report to google that npm team is incapable of fixing two years
old bugs. They are clearly YEARS away from being production ready.

**Comment by agalazis** [comment]
for  me even downloading didn't work for a specific package even when trying to clean install all gloaba modules not sure if it's actually an npm issue anymore xD

**Comment by fabrikate** [comment]
For me I get this issue when I switch my versions of node. ( Work is 4.2, Projects I use 7.5 ). Two work around are to use homebrew to uninstall then install npm OR create a VM.

**Comment by BrianO** [comment]
I have followed the tip above by "jessaustin" about removing Node 7.*.* version and going back to 6.9 version. I notice the Node website says "Latest LTS Version: v6.9.5 (includes npm 3.10.10)", but when I do "npm --version", my machine now says 2.3.0.

Should i try to update NPM to a higher version now? I do see my Dependencies errors are gone in Visual Studio 2015 Core project, but this is after so many changes, I may not be in the clear and just getting lucky that the package update succeeded somewhere along the way..

Thanks

**Comment by danhouldsworth** [comment]
I've just recompiled node from source (now : node v7.5 / npm v4.1.2) and still broken. Frustratingly, I followed the earlier advice to delete node_modules/ and so now I'm stuck!

```
npm ERR! Linux 4.4.44-39.55.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by vitalygoji** [comment]
Some people depend on that tool. Is word "lawsuit" sound familiar to NPM
team?

**Comment by agalazis** [comment]
LOL. Don't do open source, worst case scenario you will get sued. Just kidding, I am sure they are covered by their license. @vitalygoji What did you do about it? did you do a pull request and they didn't accept it?

**Comment by vitalygoji** [comment]
I can't believe that they got used by lots of people. What did google and
GitHub people think when they started using this unsupported crap? This bug
is several years old now

**Comment by jcastrov** [comment]
```
$ node -v 
7.5.0

$ npm -v 
4.2.0
```
Still with this issue

**Comment by doapp-ryanp** [comment]
I use the [`n` tool](https://github.com/tj/n) to manage switching between node (and the bundled npm) versions.

To fix this error, I simply removed npm from the global space (macOS): `sudo rm -rf /usr/local/lib/node_modules/npm`

I then re-ran `sudo n latest`.  This will re-install npm.  When switching back to previous version of node just run `sudo n 4.3.2`.

To summarise:

```fish
> sudo rm -rf /usr/local/lib/node_modules/npm
> sudo n latest
> node --version
v7.7.1
> npm --version
4.1.2
> sudo n 4.3.2
> npm --version
2.14.12
```

**Comment by rsibanez89** [comment]
>node -v
v7.7.1
>npm -v
4.1.2

Works fine for me.
For changing npm version
>npm install -g npm@4.1.2

**Comment by JohnnyWalkerDesign** [comment]
@doapp-ryanp Thanks! Your solution was the one that worked for me. 

Frustrating bug!

**Comment by codinronan** [comment]
In my case, the problem was bower - I was on 1.7.3, Node 7.7.4, npm 4.1. Upgrading Bower to 1.8.0 solved the issue for me.

**Comment by agalazis** [comment]
since the issue is upgrading one solution is docker... do clean builds/runs in docker xD

**Comment by samvloeberghs** [comment]
going back to v`6.9.5` fixed it for me. Easily achieved with `nvm`

**Comment by vanessarusu** [comment]
deleting the node_modules and running npm install worked for me!

**Comment by siddo420** [comment]
@vanessarusu did you delete global node_modules folder?

rm -rf /usr/local/lib/node_modules/

**Comment by siddo420** [comment]
I renamed the folder and tried but didn't work

**Comment by shubham-chaudhari** [comment]
npm -g install npm@next resolved for me....

**Comment by pyotrritchie** [comment]
$ npm install
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'internal/fs'

npm -v 5.3.0
node -v v8.4.0

I had this issue on npm 4.2.0 and node 7.8.0 so updated to the above and still having the same issue.

**Comment by guntram** [comment]
On Windows_NT 6.1.7601, removing the `...\AppData\Roaming\npm\node_modules` worked for me.
After that, I could `npm install` inside my project root folder.
I rolled back Node and npm to (node: 8.1.4 / npm: 5.0.3), hoping that this "you are not admin/root" stuff doesn't come back ;)

EDIT: I did not get the error again with the mentioned versions.

**Comment by Jero786** [comment]
```
➜  npm -v
3.10.10
➜  node -v
v6.9.5
```

Works fine for me too!

**Comment by alexey-sh** [comment]
`nvm install v6.9.5` works. (+reinstall node modules)
