### ISSUE TITLE
On clean node v10.5.0 install, npm install yelds asyncWrite is not a function and pna.nextTick is not a function

### ISSUE THREAD

**Issue by trygve-lie** [npm/npm#21049]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Clean install of node version 10.5.0 on Ubuntu 17.10. Not using n or any other node install managers.

Node is installed by downloading the official tar file then compiled and installed with the following:

```sh
./configure
make
make install
```

When running `npm install` in any module the following is yeld and nothing gets installed:

```sh
npm ERR! asyncWrite is not a function
npm ERR! asyncWrite is not a function
npm ERR! asyncWrite is not a function
npm ERR! asyncWrite is not a function
npm ERR! asyncWrite is not a function
npm ERR! asyncWrite is not a function
npm ERR! asyncWrite is not a function
npm ERR! asyncWrite is not a function
npm ERR! asyncWrite is not a function
npm ERR! asyncWrite is not a function
npm ERR! asyncWrite is not a function
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/trygve/.npm/_logs/2018-06-22T12_37_57_401Z-debug.log
```

Have tried to delete global cache and removed `node_modules` folder in the modules I'm installing in without any effect on the issue.

#### How can the CLI team reproduce the problem?

Run `npm install` in any module which has dependencies.

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: v10.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Ubuntu 17.10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Output of the error log created by npm:

```sh
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@6.1.0
3 info using node@v10.5.0
4 verbose npm-session 74c70565c1c3bb8b
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall ttl-mem-cache@4.0.0
7 info lifecycle ttl-mem-cache@4.0.0~preinstall: ttl-mem-cache@4.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 9ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
16 silly install loadAllDepsIntoIdealTree
17 verbose stack TypeError: asyncWrite is not a function
17 verbose stack     at onwrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:480:7)
17 verbose stack     at WritableState.onwrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:180:5)
17 verbose stack     at WriteStream.to [as _worker] (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/cache.js:154:13)
17 verbose stack     at WriteStream._write (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:35:13)
17 verbose stack     at doWrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
17 verbose stack     at writeOrBuffer (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
17 verbose stack     at WriteStream.Writable.write (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:334:11)
17 verbose stack     at WriteStream.to [as _worker] (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/cache.js:171:25)
17 verbose stack     at WriteStream._write (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:35:13)
17 verbose stack     at doWrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
17 verbose stack     at writeOrBuffer (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
17 verbose stack     at WriteStream.Writable.write (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:334:11)
17 verbose stack     at WriteStream.to [as _worker] (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/cache.js:182:19)
17 verbose stack     at WriteStream._write (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:35:13)
17 verbose stack     at doWrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
17 verbose stack     at writeOrBuffer (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
18 verbose cwd /home/trygve/Dev/ttl-mem-cache
19 verbose Linux 4.13.0-45-generic
20 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
21 verbose node v10.5.0
22 verbose npm  v6.1.0
23 error asyncWrite is not a function
24 verbose exit [ 1, true ]
```

**Comment by legodude17** [comment]
Do you use a node version manager?

**Comment by cedx** [comment]
Same problem here : Ubuntu 18.04 with Node 10.5.0 / npm 6.1.0. Using a bare install (i.e. the tar.xz archive).

**Comment by bangbang93** [comment]
same here with n as node version manager
```
➜  _logs npm i npm -g
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bangbang93/.npm/_logs/2018-06-23T06_02_13_481Z-debug.log
➜  _logs node -v
v10.5.0
➜  _logs npm -v
6.1.0
```
npm log
```0 info it worked if it ends with ok
1 verbose cli [ '/Users/bangbang93/n/bin/node',
1 verbose cli   '/Users/bangbang93/n/bin/npm',
1 verbose cli   'i',
1 verbose cli   'npm',
1 verbose cli   '-g' ]
2 info using npm@6.1.0
3 info using node@v10.5.0
4 verbose npm-session acd5b1a910d90676
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 verbose stack TypeError: asyncWrite is not a function
7 verbose stack     at onwrite (/Users/bangbang93/n/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:480:7)
7 verbose stack     at WritableState.onwrite (/Users/bangbang93/n/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:180:5)
7 verbose stack     at WriteStream.to [as _worker] (/Users/bangbang93/n/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/cache.js:154:13)
7 verbose stack     at WriteStream._write (/Users/bangbang93/n/lib/node_modules/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:35:13)
7 verbose stack     at doWrite (/Users/bangbang93/n/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
7 verbose stack     at writeOrBuffer (/Users/bangbang93/n/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
7 verbose stack     at WriteStream.Writable.write (/Users/bangbang93/n/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:334:11)
7 verbose stack     at WriteStream.to [as _worker] (/Users/bangbang93/n/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/cache.js:171:25)
7 verbose stack     at WriteStream._write (/Users/bangbang93/n/lib/node_modules/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:35:13)
7 verbose stack     at doWrite (/Users/bangbang93/n/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
7 verbose stack     at writeOrBuffer (/Users/bangbang93/n/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
7 verbose stack     at WriteStream.Writable.write (/Users/bangbang93/n/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:334:11)
7 verbose stack     at WriteStream.to [as _worker] (/Users/bangbang93/n/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/cache.js:182:19)
7 verbose stack     at WriteStream._write (/Users/bangbang93/n/lib/node_modules/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:35:13)
7 verbose stack     at doWrite (/Users/bangbang93/n/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
7 verbose stack     at writeOrBuffer (/Users/bangbang93/n/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
8 verbose cwd /Users/bangbang93/.npm/_logs
9 verbose Darwin 17.5.0
10 verbose argv "/Users/bangbang93/n/bin/node" "/Users/bangbang93/n/bin/npm" "i" "npm" "-g"
11 verbose node v10.5.0
12 verbose npm  v6.1.0
13 error asyncWrite is not a function
14 verbose exit [ 1, true ]
```

**Comment by niicojs** [comment]
same on windows using official installer
edit: managed to make it work by uninstalling, manually delete all files in npm and npm-cache then reinstall.

**Comment by trygve-lie** [comment]
> Do you use a node version manager?

No node version manager in my end. I install by downloading the official tar file then:

```sh
./configure
make
make install
```

**Comment by fishlao** [comment]
i am not clear how should i do ,i clean up node_modules in my project and reinstall it,but it didn't work.

**Comment by steeply** [comment]
MacOs 10.9.5, node -v 10.5.0, npm -v 6.1.0

on all projects =(

```
git:(master) ✗ npm i
asyncWrite(afterWrite, stream, state, finished, cb);
^

npm ERR! asyncWrite is not a function

```

**Comment by trygve-lie** [comment]
This issue seems to be obsolete in node.js v10.6.0. At least it is for me.

Feel free to close.

**Comment by bangbang93** [comment]
```
➜  ops-backend git:(feature/package-group-selection) ✗ npm i faker   
npm ERR! pna.nextTick is not a function
npm ERR! pna.nextTick is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bangbang93/.npm/_logs/2018-07-05T01_57_41_647Z-debug.log
➜  ops-backend git:(feature/package-group-selection) ✗ node -v    
v10.6.0
➜  ops-backend git:(feature/package-group-selection) ✗ npm -v     
6.1.0
➜  ops-backend git:(feature/package-group-selection) ✗ 
```
still errors at 10.6.0

**Comment by cedx** [comment]
Same: still no luck with a clean install of Node.js 10.6.0 / npm 6.1.0 on Ubuntu 18.04 (reproduced on 2 machines).

```
$ npm update
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function
```

**Comment by mdrobny** [comment]
I had the same errors when using Node.js 10.5.0 & npm 6.1.0 on macOS with Node.js installed via `n`.
- I removed all Node.js versions
- `rm -r /usr/local/lib/node_modules`
- `rm -r ~/.npm`

I installed node 10.6.0 via `brew` and I don't have `asyncWrite is not a function` or `pna.nextTick is not a function` errors anymore.
I don't say it's `n's` fault but it may be part of the problem

**Comment by linjiajian999** [comment]
@mdrobny, I have same problem on macOS. I reinstalled the nodejs, and then the problem resolved

**Comment by trygve-lie** [comment]
I retract my comment on this working on node 10.6.0. I managed to install a couple of times, but now its just yelding the same error as initially reported.
