### ISSUE TITLE
After update node js to 6.6.0 npm not working

### ISSUE THREAD

**Issue by fprotano** [npm/npm#17890]
Hello, guys i spent 2 hours of my saturday to solve a problem.
I'm searching for create a very simple app with ionic 2 and angularjs2 . This my steps

1) I installed nodejs (current was 4.2.6)
2) I installed npm
3) i installed ionic and cordova
During step 3 npm informed me that minimun version of nodejs is 6

4) i create a project with ionic by command ionic start test --v2
5) i upgraded the nodejs with command 
      npm install -g n 
      n latest

6) i build the project by command npm run build

My OS is Ubuntu 16
Below the error in log

 

2 info using npm@3.5.2
3 info using node@v8.2.1
4 verbose stack Error: Cannot find module 'ansi'
4 verbose stack     at Function.Module._resolveFilename (module.js:485:15)
4 verbose stack     at Function.Module._load (module.js:437:25)
4 verbose stack     at Module.require (module.js:513:17)
4 verbose stack     at require (internal/module.js:11:18)
4 verbose stack     at Object.<anonymous> (/usr/share/npm/lib/ls.js:15:13)
4 verbose stack     at Module._compile (module.js:569:30)
4 verbose stack     at Object.Module._extensions..js (module.js:580:10)
4 verbose stack     at Module.load (module.js:503:32)
4 verbose stack     at tryModuleLoad (module.js:466:12)
4 verbose stack     at Function.Module._load (module.js:458:3)

There's anybody can help me?
