### ISSUE TITLE
Cannot find module 'github-url-from-git'

### ISSUE THREAD

**Issue by maydanchi** [npm/npm#11383]
Here is the npm-debug.log file:

---------

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'list',
1 verbose cli   '-g',
1 verbose cli   '--depth=0' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose stack Error: Cannot find module 'github-url-from-git'
4 verbose stack     at Function.Module._resolveFilename (module.js:339:15)
4 verbose stack     at Function.Module._load (module.js:290:25)
4 verbose stack     at Module.require (module.js:367:17)
4 verbose stack     at require (internal/module.js:16:19)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:2:22)
4 verbose stack     at Module._compile (module.js:413:34)
4 verbose stack     at Object.Module._extensions..js (module.js:422:10)
4 verbose stack     at Module.load (module.js:357:32)
4 verbose stack     at Function.Module._load (module.js:314:12)
4 verbose stack     at Module.require (module.js:367:17)
5 verbose cwd /Applications/MAMP/htdocs/Clients/live/mattelplay/cms
6 error Darwin 13.0.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "list" "-g" "--depth=0"
8 error node v5.5.0
9 error npm  v3.3.12
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'github-url-from-git'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by maydanchi** [comment]
any update regarding to this issue?

**Comment by ashleygwilliams** [comment]
i cannot reproduce this on my machine with the same node and npm versions as you have.

**Comment by ashleygwilliams** [comment]
looks like this may be a dupe of https://github.com/nodejs/node/issues/3540
could you read through and see if that fixes your issue? specifically https://github.com/nodejs/node/issues/3540#issuecomment-165960060, which suggests you `npm install -g github-url-from-git`

please open a new issue if you continue to have this problem.

**Comment by beavis28** [comment]
I saw this issue when I upgraded node 4 to 6 on windows via msi.
Seems like this is installer bug.
To fix this, do this.

1 uninstall 4x version
2 remove program files/nodejs
3 remove %appdata%/npm and nvmcache
4 install 6.9.1

This will fix the issue

**Comment by whit537** [comment]
Ftr, http://stackoverflow.com/a/11178106 worked for me to remove a broken node 6.9.1 upgrade on macOS 10.10.5. Reinstalling worked as @beavis28 suggests.

**Comment by DanHaddock** [comment]
@beavis28 Legend! Thank you so much for your help. Also, if anyone is unsure about how to carry out step 1 this guide was very helpful: [http://benznext.com/completely-uninstall-node-js-from-mac-os-x/]

**Comment by n122vu** [comment]
Ran into this issue while trying to install the TypeScript compiler.  The solution beavis28 provided worked perfectly.  Node.js version 6.11.
