### ISSUE TITLE
npmlog not found after updating npm in Docker

### ISSUE THREAD

**Issue by e-ts** [npm/npm#18278]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
In a docker container, after updating to 5.4.0, all npm commands immediately exits with a stack trace about npmlog module not being found.

I have tested with official images node:latest and node:alpine and they both have the same problem.

On a Fedora 26 installation the update to 5.4.0 did not break my installation like this so the issue is possibly with official node images.

Notably, `npm i -g npm` (without the version tag) produces the same error, so this probably has nothing to do with 5.4. The output for the update without version tag is available in a gist.
https://gist.github.com/e-ts/2caf33c9344d4611e0c7ede694f5eb22

#### How can the CLI team reproduce the problem?
```
docker run -i -t node sh
npm i -g npm@5.4.0
npm -v
```

```
module.js:491
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:22:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)

```

There is no npm-debug.log produced.

### supporting information:

 - Before update, `npm -v` prints: `5.3.0`
 - `node -v` prints: `v.8.4.0`
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run: Sweden
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

See also: https://github.com/npm/npm/issues/15225

**Comment by mastilver** [comment]
You should try: https://github.com/npm/npm/issues/16807#issuecomment-313591975

**Comment by e-ts** [comment]
Thank you @mastilver that works.

**Comment by whymarrh** [comment]
See also: #18325
