### ISSUE TITLE
npm v5 incorrect install

### ISSUE THREAD

**Issue by nathanbowser** [npm/npm#17065]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm isn't installing all the dependencies of a project. e.g.
`raw-stacktrace` (https://github.com/jb55/node-raw-stacktrace/blob/master/package.json) has a dependency on `traceback`, but traceback is not installed.

#### How can the CLI team reproduce the problem?
```
$ mkdir foo
$ cd foo
$ npm i raw-stacktrace
$ ls node_modules
```
traceback isn't installed.

Note: `npm install traceback` is totally fine.

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v6.10.2
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Reproduced on OS X and Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Does `raw-stacktrace` work? What is the result of `ls -R node_modules/`?

**Comment by nathanbowser** [comment]
1. No, it's missing the dependency that it specifies in package.json.
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'traceback'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at TraceEmitter (/Users/koopa/Desktop/foo/node_modules/raw-stacktrace/index.js:68:24)
    at Object.<anonymous> (/Users/koopa/Desktop/foo/test.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

```
2. 
```
[koopa@dash-dev foo]$ ls -R node_modules/
raw-stacktrace

node_modules//raw-stacktrace:
Makefile	Readme.md	example.js	index.js	package.json	test

node_modules//raw-stacktrace/test:
index.js
```

**Comment by legodude17** [comment]
Does `npm i traceback@>=0.3.0&&<0.4.0` work?

**Comment by nathanbowser** [comment]
I don't know, but I put clear instructions on reproducing; you're more than welcome to run that command to see if it works with v5.0.3. It's probably faster than asking me to run it.

**Comment by nathanbowser** [comment]
This might be a duplicate of #16902. One commenter mentioned deleting the package-lock.json but that doesn't seem to make a difference for me, as I can reproduce this in a fresh directory.

**Comment by nathanbowser** [comment]
Using yarn, I see a message:

```
error raw-stacktrace@1.0.0: The engine "node" is incompatible with this module. Expected version "~0.6.8".
error Found incompatible module
```

npm v4.x install this module just fine. npm v5.x doesn't install and fails silently, so maybe it's best to just spit out a warning/error in this case?

**Comment by kenany** [comment]
`>=0.3.0 && <0.4.0` is only a loosely valid `node-semver` range. I can confirm that https://github.com/npm/npm/pull/17007 fixes this; should be in the next release (this week, I think).
