### ISSUE TITLE
Node 7.10.0 upgrade causes `Error: Cannot find module './request'`

### ISSUE THREAD

**Issue by EvNaverniouk** [npm/npm#16566]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

After upgrading from node 7.9.0 to 7.10.0 I can no longer use `npm` due this error:

```
Error: Cannot find module './request'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/index.js:144:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

This is reported several times after any `npm ___` command such as `npm run test`.

This issue was not occurring when using `node` 7.9.0

#### How can the CLI team reproduce the problem?

I am using MacOS and starting with `node@7.9.0` I ran:

```
brew update
brew upgrade
```

And then ran:

```
npm run test
```

inside my project. This caused the error to appear.

### supporting information:

 - `npm -v` prints: Fails with `Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/npm/package.json'`
 - `node -v` prints: `v7.10.0`
 - `npm config get registry` prints: Fails with `Error: Cannot find module './request'`
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [X] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by EvNaverniouk** [comment]
I was able to fix this issue by running:

```
brew uninstall node
sudo rm -rf /usr/local/lib/node_modules/
brew install node
```

Looks like something in my global node modules got corrupted during the upgrade.

Is this something the `npm` team still wants to look into?

**Comment by zkat** [comment]
@EvNaverniouk this looks more like an installer issue. There's not much we can do if external packages hose npm installs on us -- we kinda need npm files to be there in order to work at all :\

So I'm just gonna close this. Thanks for taking the time to file the issue, and I'm glad you managed to get it resolved! <3
