### ISSUE TITLE
npmlog not found error on nodejs v5

### ISSUE THREAD

**Issue by calidion** [npm/npm#11350]
```
0.06s$ npm --version
module.js:341
    throw err;
    ^
Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /home/travis/.nvm/versions/node/v5.5.0/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v5.5.0/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

**Comment by calidion** [comment]
see: 
https://travis-ci.org/node-weixin/node-weixin-express/jobs/105821268

for detailed info.

**Comment by zkat** [comment]
This looks like a plain installation hiccup: Can you try rerunning that one test, or possibly changing `NPM_VERSION` to `3.6`?

**Comment by calidion** [comment]
fixed when updated to 3.5
