### ISSUE TITLE
Cannot find module 'github-url-from-username-repo'

### ISSUE THREAD

**Issue by antsofthesky** [npm/npm#15707]
After upgrading Node to v6.9.5 and NPM to v3.10.10, I'm getting this error all of a sudden any time I try to do anything with NPM (install, etc.). I'm on macOS Sierra 10.12.3.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose stack Error: Cannot find module 'github-url-from-username-repo'
4 verbose stack     at Function.Module._resolveFilename (module.js:469:15)
4 verbose stack     at Function.Module._load (module.js:417:25)
4 verbose stack     at Module.require (module.js:497:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:8:22)
4 verbose stack     at Module._compile (module.js:570:32)
4 verbose stack     at Object.Module._extensions..js (module.js:579:10)
4 verbose stack     at Module.load (module.js:487:32)
4 verbose stack     at tryModuleLoad (module.js:446:12)
4 verbose stack     at Function.Module._load (module.js:438:3)
6 error Darwin 16.4.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
8 error node v6.9.5
9 error npm  v3.10.10
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'github-url-from-username-repo'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by antsofthesky** [comment]
I was able to fix this for anyone wondering. I removed NPM from my computer and re-installed using the installer from the nodejs.org site.
