### ISSUE TITLE
install.sh fails because bin/read-package-json.js was removed

### ISSUE THREAD

**Issue by ericvpeters** [npm/npm#18524]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
https://github.com/npm/npm/blob/latest/scripts/install.sh fails because bin/read-package-json.js was removed. 

The file was removed in commit https://github.com/npm/npm/commit/9462e5d9cfbaa50218de6d0a630d6552e72ad0a8 . However, that file is referenced at the following line https://github.com/npm/npm/blob/e2745004628e595b5017588aae794638568ef0fc/scripts/install.sh#L211 
#### How can the CLI team reproduce the problem?
curl -L https://www.npmjs.org/install.sh | sh

**Comment by fones** [comment]
Error is in version 5.4.0 and above.
I have downloaded script, modify to get 5.3.0, there was no error, but npm was not installed.

```
[ec2-user tmp]$ ls -l /usr/bin | grep npm
lrwxrwxrwx   1 root root         38 Sep 15 18:43 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxrwxrwx   1 root root         38 Sep 15 18:30 npx -> ../lib/node_modules/npm/bin/npx-cli.js
[ec2-user tmp]$ ls -l /usr/lib/node_modules/
total 4
lrwxrwxrwx 1 root     root       30 Sep 15 18:43 npm -> ../../../tmp/npm.26004/package
drwxr-xr-x 2 ec2-user ec2-user 4096 Sep 15 18:41 undefined
```

Temp folder `/tmp/npm.26004` was deleted by script.

**Comment by eric-schleicher** [comment]
^ having this exact same issue

on ubuntu 16.04 LTS

**Comment by gavi** [comment]
This is still a problem

**Comment by tehfailsafe** [comment]
Installed node with Homebrew --without-npm.  Attempting to install npm now throws this error. Any other fixes while this is being worked on?

**Comment by winteraz** [comment]
this fails on centos too...npm seems to be no different than most of its packages (reliability wise)

**Comment by chicken-suop** [comment]
Same thing here.

```
$ curl -L https://www.npmjs.org/install.sh | sudo sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   185  100   185    0     0     84      0  0:00:02  0:00:02 --:--:--    84
100  6255  100  6255    0     0   1213      0  0:00:05  0:00:05 --:--:--  2573
tar=/usr/bin/tar
version:
bsdtar 2.8.3 - libarchive 2.8.3
install npm@latest
fetching: https://registry.npmjs.org/npm/-/npm-5.6.0.tgz
module.js:471
    throw err;
    ^

Error: Cannot find module '/private/tmp/npm.83526/package/bin/read-package-json.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
removed 363 packages in 24.76s
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
+ npm@5.6.0
updated 5 packages in 4.02s
It worked
```

**Comment by RedKage** [comment]
Same here. After building node (configure + make install) on an unix box without sudo.
My prefix is $HOME/.local.

I downloaded the install.sh and did this
`~/.local/sources/node-9.4.0 $ npm_config_prefix=$HOME/.local npm_debug=1 sh install.sh`

```
Running in debug mode.
Note that this requires bash or zsh.
+ set -o pipefail
+ npm_config_loglevel=verbose
+ export npm_config_loglevel
++ which node
+ node=/home/redkage/.local/bin/node
+ ret=0
+ '[' 0 -eq 0 ']'
+ '[' -x /home/redkage/.local/bin/node ']'
+ exit 0
+ TMP=/home/redkage/.tmp
+ '[' x/home/redkage/.tmp = x ']'
+ TMP=/home/redkage/.tmp/npm.32279
+ rm -rf /home/redkage/.tmp/npm.32279
+ mkdir /home/redkage/.tmp/npm.32279
+ '[' 0 -ne 0 ']'
+ BACK=/home/redkage/.local/sources/node-9.4.0
+ ret=0
+ tar=
+ '[' -z '' ']'
+ tar=
+ '[' -z '' ']'
++ which tar
+ tar=/bin/tar
+ ret=0
+ '[' 0 -eq 0 ']'
+ '[' -x /bin/tar ']'
+ echo tar=/bin/tar
tar=/bin/tar
+ echo version:
version:
+ /bin/tar --version
tar (GNU tar) 1.29
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
+ ret=0
+ '[' 0 -eq 0 ']'
+ exit 0
+ MAKE=NOMAKE
+ '[' xNOMAKE = x ']'
+ make=NOMAKE
+ '[' -x NOMAKE ']'
+ make=NOMAKE
+ '[' -x /bin/bash ']'
+ exit 0
++ /home/redkage/.local/bin/node --version
+ node_version=v9.4.0
+ ret=0
+ '[' 0 -ne 0 ']'
+ t=
+ '[' -z '' ']'
+ case $node_version in
+ echo 'install npm@latest'
install npm@latest
+ t=latest
++ curl -SsL https://registry.npmjs.org/npm/latest
++ sed -e 's/^.*tarball":"//'
++ sed -e 's/".*$//'
++ echo ''
+ url=https://registry.npmjs.org/npm/-/npm-5.6.0.tgz
+ ret=0
+ '[' xhttps://registry.npmjs.org/npm/-/npm-5.6.0.tgz = x ']'
+ '[' 0 -ne 0 ']'
+ echo 'fetching: https://registry.npmjs.org/npm/-/npm-5.6.0.tgz'
fetching: https://registry.npmjs.org/npm/-/npm-5.6.0.tgz
+ cd /home/redkage/.tmp/npm.32279
+ curl -SsL https://registry.npmjs.org/npm/-/npm-5.6.0.tgz
+ /bin/tar -xzf -
+ cd /home/redkage/.tmp/npm.32279/package
++ /home/redkage/.local/bin/node bin/read-package-json.js package.json version
module.js:557
    throw err;
    ^

Error: Cannot find module '/mnt/sdb1/redkage/.tmp/npm.32279/package/bin/read-package-json.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
+ ver=
+ isnpm10=0
+ '[' 0 -eq 0 ']'
+ '[' -d node_modules ']'
+ /home/redkage/.local/bin/node node_modules/semver/bin/semver -v '' -r 1
+ ret=0
+ '[' 0 -eq 1 ']'
+ '[' 0 -ne 0 ']'
+ '[' xprefix=/home/redkage/.local = x ']'
+ echo './configure prefix=/home/redkage/.local'
./configure prefix=/home/redkage/.local
+ echo prefix=/home/redkage/.local
+ '[' NOMAKE = NOMAKE ']'
+ exit 0
+ '[' NOMAKE = NOMAKE ']'
+ /home/redkage/.local/bin/node bin/npm-cli.js rm npm -gf
npm info it worked if it ends with ok
npm verb cli [ '/mnt/sdb1/redkage/.local/bin/node',
npm verb cli   '/mnt/sdb1/redkage/.tmp/npm.32279/package/bin/npm-cli.js',
npm verb cli   'rm',
npm verb cli   'npm',
npm verb cli   '-gf' ]
npm info using npm@5.6.0
npm info using node@v9.4.0
npm WARN using --force I sure hope you know what you are doing.
npm verb npm-session 02b9f4c059864cfc
npm verb correctMkdir /home/redkage/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/redkage/.npm/_locks/staging-bbbb194f3259dfd7.lock for /home/redkage/.local/lib/node_modules/.staging
npm verb unlock done using /home/redkage/.npm/_locks/staging-bbbb194f3259dfd7.lock for /home/redkage/.local/lib/node_modules/.staging
up to date in 0.067s
npm verb exit [ 0, true ]
npm info ok
+ /home/redkage/.local/bin/node bin/npm-cli.js install -gf
npm info it worked if it ends with ok
npm verb cli [ '/mnt/sdb1/redkage/.local/bin/node',
npm verb cli   '/mnt/sdb1/redkage/.tmp/npm.32279/package/bin/npm-cli.js',
npm verb cli   'install',
npm verb cli   '-gf' ]
npm info using npm@5.6.0
npm info using node@v9.4.0
npm WARN using --force I sure hope you know what you are doing.
npm verb npm-session 9feda4c07cbc9ed7
npm verb correctMkdir /home/redkage/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/redkage/.npm/_locks/staging-bbbb194f3259dfd7.lock for /home/redkage/.local/lib/node_modules/.staging
npm info lifecycle npm@5.6.0~preinstall: npm@5.6.0
npm info linkStuff npm@5.6.0
npm verb linkBins npm@5.6.0
npm verb linkBins [ { npm: './bin/npm-cli.js', npx: './bin/npx-cli.js' },
npm verb linkBins   '/home/redkage/.local/bin',
npm verb linkBins   true ]
npm verb linkMans npm@5.6.0
npm verb unlock done using /home/redkage/.npm/_locks/staging-bbbb194f3259dfd7.lock for /home/redkage/.local/lib/node_modules/.staging
npm verb stack Error: ENOENT: no such file or directory, chmod '/home/redkage/.local/lib/node_modules/npm/bin/npm-cli.js'
npm verb cwd /mnt/sdb1/redkage/.tmp/npm.32279/package
npm verb Linux 4.9.20-hardened-whatbox-r1
npm verb argv "/mnt/sdb1/redkage/.local/bin/node" "/mnt/sdb1/redkage/.tmp/npm.32279/package/bin/npm-cli.js" "install" "-gf"
npm verb node v9.4.0
npm verb npm  v5.6.0
npm ERR! path /home/redkage/.local/lib/node_modules/npm/bin/npm-cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/redkage/.local/lib/node_modules/npm/bin/npm-cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm verb exit [ -2, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/redkage/.npm/_logs/2018-01-16T14_29_14_008Z-debug.log
+ ret=254
+ '[' 254 -ne 0 ']'
+ echo 'It failed'
It failed
+ exit 254
```

**Comment by valera-rozuvan** [comment]
Just tried installing via the `install.sh` script, had a similar error:

```
root@computer-58677f:/home/valera/Downloads# ./install.sh 
tar=/bin/tar
version:
tar (GNU tar) 1.29
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
install npm@latest
fetching: https://registry.npmjs.org/npm/-/npm-5.6.0.tgz
module.js:327
    throw err;
    ^

Error: Cannot find module '/tmp/npm.3893/package/bin/read-package-json.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
up to date in 0.548s
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.6.0
added 1 package in 23.763s
It worked
```

 Even though the script said that **"It worked"**, I am unable to execute `npm`:

```
valera@computer-58677f:~$ npm
bash: npm: command not found
```

Upon further inspection:

```
root@computer-58677f:~# ls -a -h -l /usr/bin/npm
lrwxrwxrwx 1 root root 38 Jan 21 15:11 /usr/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js
root@computer-58677f:~# ls -a -h -l /usr/lib/node_modules/npm 
lrwxrwxrwx 1 root root 29 Jan 21 15:11 /usr/lib/node_modules/npm -> ../../../tmp/npm.3893/package
root@computer-58677f:~# ls -a -h -l /tmp/npm.3893
ls: cannot access '/tmp/npm.3893': No such file or directory
```

Information about my system:

- Node version `4.8.2`
- Linux distro `Debian GNU/Linux 9 (stretch)`
- Linux kernel `Linux computer-58677f 4.9.0-5-686-pae #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) i686 GNU/Linux`

**Comment by lukidoescode** [comment]
Same here.
Node Version: 8.9.4
I am trying to install npm 5.6.0. For some reason it installs everything into /tmp. THen it  creates a symlink to that installation instead of copying it. Then it deletes the /tmp/npm* folder. Very odd. It can't work. I did a manual installation now.

**Comment by mauris** [comment]
One workaround that worked for me was to download the source code, and run `scripts/install.sh` directly. You can run the following in your shell:

    NPM_VER=5.7.1
    wget https://registry.npmjs.org/npm/-/npm-${NPM_VER}.tgz
    tar xzf npm-${NPM_VER}.tgz
    cd package
    ./scripts/install.sh

The `install.sh` from `https://www.npmjs.com/install.sh` downloads this same tgz anyway.

**Comment by seabb** [comment]
@mauris Yes, this workaround works great, thank you for posting this!
1 comment I would add is not to forget to remove the existing /npm sym-link created by the previous attempts before trying the manual approach.

cd /usr/local/lib/node_modules
unlink npm

**Comment by snowghost24** [comment]
Im trying whats written above and getting the following message.

`~ wget https://registry.npmjs.org/npm/-/npm-$\(NPM_VER\).tgz
--2018-02-24 08:05:30--  https://registry.npmjs.org/npm/-/npm-$(NPM_VER).tgz
Resolving registry.npmjs.org (registry.npmjs.org)... 151.101.4.162
Connecting to registry.npmjs.org (registry.npmjs.org)|151.101.4.162|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2018-02-24 08:05:30 ERROR 500: Internal Server Error.`

**Comment by mauris** [comment]
@snowghost24 replace all instances of `$(NPM_VER)` with "5.6.0"

**Comment by snowghost24** [comment]
oh I see it. Thanks

**Comment by ronalson** [comment]
I don't have much experience with node and I was using [n](https://github.com/tj/n) as my version manager tool. It was working fine for a while, however while following some tutorials yesterday everything started to go south.

I went through tutorials asking me to verify and clean my npm cache, reinstalled node (via n) and now npm is not working. All tutorials I come through points me to reinstall npm using the following command
```bash
curl -L https://www.npmjs.org/install.sh | sh
```

But this does not work. Now I'm stuck at this error:

```bash
module.js:540
    throw err;
    ^

Error: Cannot find module '/private/tmp/npm.972/package/bin/read-package-json.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
added 1 package in 1.356s
```
Can someone point me to the right direction? I'm not sure I understood how to follow @mauris workaround.

**Comment by woodcockjosh** [comment]
Last line of @mauris solution didn't work on 5.7.0. Had to change it. Also I had to put inside a install.sh file

```
NPM_VER=5.7.0
wget https://registry.npmjs.org/npm/-/npm-${NPM_VER}.tgz
tar xzf npm-${NPM_VER}.tgz
cd package
./scripts/install.sh
```

**Comment by zkat** [comment]
https://github.com/npm/npm/commit/5ee55dc71b8b74b8418c3d5ec17483a07b3b6777#diff-80423f13d45b53af35790ffc6009be4d already updated this, but the script didn't get deployed to production. I've pinged the registry folks about it.

**Comment by zkat** [comment]
https://github.com/npm/npm/commit/5ee55dc71b8b74b8418c3d5ec17483a07b3b6777#diff-80423f13d45b53af35790ffc6009be4d already updated this, but the script didn't get deployed to production. I've pinged the registry folks about it.

**Comment by lawrencelm** [comment]
Had the same problem. As zkat mentioned, it's fixed but not deployed to https://www.npmjs.com/install.sh. Solved it by running:

`curl -L https://raw.githubusercontent.com/npm/npm/latest/scripts/install.sh | sh`

EDIT: I realized that, while I don't get error messages, it seems like npm is not downloaded

**Comment by lawrencelm** [comment]
I tried @mauris's solution and I am getting the following error:

```
tar=/usr/bin/tar
version:
bsdtar 2.8.3 - libarchive 2.8.3
install npm@5.7.1
fetching: http://registry.npmjs.org/npm/-/npm-5.7.1.tgz
added 1 package from 1 contributor in 1.746s
sh: rimraf: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! npm@5.7.1 prepare: `node bin/npm-cli.js --no-timing prune --prefix=. --no-global && rimraf test/*/*/node_modules && make -j4 doc`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the npm@5.7.1 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lawrence/.npm/_logs/2018-04-30T11_33_15_631Z-debug.log
npm ERR! code E404
npm ERR! 404 Not Found: 2.318s@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lawrence/.npm/_logs/2018-04-30T11_33_18_012Z-debug.log
It failed

```

EDIT: Fixed my issue by replacing the last line of @mauris's solution with `sudo ./scripts/install.sh`

**Comment by piot** [comment]
Same problem here. Couldn't fix it for 10.0.0.

**Comment by jamesstout** [comment]
Same error as @lawrencelm. Seems the prepare command fails?

```bash
prepare: `node bin/npm-cli.js --no-timing prune --prefix=. --no-global && rimraf test/*/*/node_modules && make -j4 doc`
# ---8<--snip--8<--
sh: rimraf: command not found
npm ERR! file sh
```

`rimraf` not found...

I followed @mauris's method, but edited `./scripts/install.sh` before running, making it change `rimraf` to `rm -rf` in the downloaded `package.json` using `sed`:

```bash
sed -i '' "s/rimraf test/rm -rf test/" package.json
```
![screen shot 2018-05-19 at 8 58 44 pm](https://user-images.githubusercontent.com/1576190/40269237-f6ee0496-5bad-11e8-90d0-74d3659c1f0f.png)

**It worked.** 

Patch here: [diffs.patch.txt](https://github.com/npm/npm/files/2019514/diffs.patch.txt)

:balloon: The script installs the [latest](https://github.com/npm/npm/blob/5ee55dc71b8b74b8418c3d5ec17483a07b3b6777/scripts/install.sh#L176) version of `npm` by default. Just FYI.

**Comment by ghost** [comment]
I followed @jamesstout approach, but placed it on line 230, right above:

`"$node" bin/npm-cli.js rm npm -gf`

Also, for my Mac, my sed was aliased from gnu-sed, so I had to use:

`sed -i "s/rimraf test/rm -rf test/" package.json`

**It worked.**

**Comment by amuktharao** [comment]
Hi,

I tried @jamesstout and @ocaballero05 approach on CentOS but still getting the same error. Should I cleanup anything from the old run before doing this. Please let me know, Thank you!!


Written by John Gilmore and Jay Fenlason.
install npm@latest
fetching: https://registry.npmjs.org/npm/-/npm-6.1.0.tgz
sed: can't read s/rimraf test/rm -rf test/: No such file or directory

/tmp/npm.131420/package/bin/npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
          ^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

/tmp/npm.131420/package/bin/npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
          ^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

/tmp/npm.131420/package/bin/npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
          ^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
It failed

**Comment by amuktharao** [comment]
I get the same error even with this command curl -L https://www.npmjs.org/install.sh | sh and curl -L https://raw.githubusercontent.com/npm/npm/latest/scripts/install.sh | sh

[root@ebdp-avdc-d011p package]# curl -L https://www.npmjs.org/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   185  100   185    0     0    220      0 --:--:-- --:--:-- --:--:--   220
100  6254  100  6254    0     0   3985      0  0:00:01  0:00:01 --:--:-- 13991
tar=/usr/bin/tar
version:
tar (GNU tar) 1.26
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
install npm@latest
fetching: https://registry.npmjs.org/npm/-/npm-6.1.0.tgz

module.js:340
    throw err;
          ^
Error: Cannot find module '/tmp/npm.165531/package/bin/read-package-json.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

/tmp/npm.165531/package/bin/npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
          ^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

/tmp/npm.165531/package/bin/npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
          ^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
It failed



curl -L https://raw.githubusercontent.com/npm/npm/latest/scripts/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5450  100  5450    0     0  11473      0 --:--:-- --:--:-- --:--:-- 11473
tar=/usr/bin/tar
version:
tar (GNU tar) 1.26
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
install npm@latest
fetching: https://registry.npmjs.org/npm/-/npm-6.1.0.tgz

module.js:340
    throw err;
          ^
Error: Cannot find module '/tmp/npm.178101/package/bin/read-package-json.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

/tmp/npm.178101/package/bin/npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
          ^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

/tmp/npm.178101/package/bin/npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
          ^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
It failed
You have new mail in /var/mail/root

**Comment by ocaballero05** [comment]
@amuktharao I was getting that error too, which is why I had to start
researching sed and found that some versions of that don't have compatible
arguments.

What if you try `-i -e` instead of `-i ''`?

**Comment by ghost** [comment]
@amuktharao I was getting that error too, which is why I had to start
researching sed and found that some versions of that don't have compatible
arguments.

What if you try 
`sed -i -e "s/rimraf test/rm -rf test/" package.json`
instead of 
`sed -i '' "s/rimraf test/rm -rf test/" package.json`?

**Comment by amuktharao** [comment]
@ocaballero05 i tried that too, it is still giving error but I can see the -i -e option available in CentOS as well. Not sure why it is not working.
sed -i -e "s/rimraf test/rm -rf test/" package.json
