### ISSUE TITLE
npm not working on mac OS 10.11  

### ISSUE THREAD

**Issue by maiernte** [npm/npm#10454]
I  want to update the npm to new version, and with any other "install" command has the same error.
The OS is OS X 10.11

can anybody help me?

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'update',
1 verbose cli   'npm',
1 verbose cli   '-g' ]
2 info using npm@2.14.7
3 info using node@v4.2.2
4 verbose stack Error: Cannot find module 'has-unicode'
4 verbose stack     at Function.Module._resolveFilename (module.js:337:15)
4 verbose stack     at Function.Module._load (module.js:287:25)
4 verbose stack     at Module.require (module.js:366:17)
4 verbose stack     at require (module.js:385:17)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-install-checks/node_modules/npmlog/node_modules/gauge/progress-bar.js:2:18)
4 verbose stack     at Module._compile (module.js:435:26)
4 verbose stack     at Object.Module._extensions..js (module.js:442:10)
4 verbose stack     at Module.load (module.js:356:32)
4 verbose stack     at Function.Module._load (module.js:311:12)
4 verbose stack     at Module.require (module.js:366:17)
4 verbose stack     at require (module.js:385:17)
5 verbose cwd /Users/mai
6 error Darwin 15.0.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "update" "npm" "-g"
8 error node v4.2.2
9 error npm  v2.14.7
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'has-unicode'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by imyejin** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

dufma555@naver.com 님께 보내신 메일 <[npm] npm cannot update, cannot install any package (#10454)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by RobWiederstein** [comment]
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'less' ]
2 info using npm@2.14.7
3 info using node@v4.2.3
4 verbose stack Error: Cannot find module 'has-unicode'
4 verbose stack     at Function.Module._resolveFilename (module.js:337:15)
4 verbose stack     at Function.Module._load (module.js:287:25)
4 verbose stack     at Module.require (module.js:366:17)
4 verbose stack     at require (module.js:385:17)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-install-checks/node_modules/npmlog/node_modules/gauge/progress-bar.js:2:18)
4 verbose stack     at Module._compile (module.js:435:26)
4 verbose stack     at Object.Module._extensions..js (module.js:442:10)
4 verbose stack     at Module.load (module.js:356:32)
4 verbose stack     at Function.Module._load (module.js:311:12)
4 verbose stack     at Module.require (module.js:366:17)
4 verbose stack     at require (module.js:385:17)
5 verbose cwd /Users/robertwiederstein
6 error Darwin 15.0.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "less"
8 error node v4.2.3
9 error npm  v2.14.7
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'has-unicode'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by RobWiederstein** [comment]
I received the same error message.  Recently upgraded to El Capitan.

[npm-debug-log.txt](https://github.com/npm/npm/files/53971/npm-debug-log.txt)

**Comment by dejewi** [comment]
Did you found solution for this?

**Comment by alexmac131** [comment]
Yes, I am having the same issue after an upgrade to the the current stable.

**Comment by alexmac131** [comment]
So, I got my own to work, I cd'd to 

cd /usr/local/lib/
rm -rf node_modules

reinstalled 

works fine

**Comment by morficus** [comment]
+1 for what @alexgorbatchev suggested.
After deleting ` /usr/local/lib/node_modules` I re-installed node and things worked again.

**Comment by SergiuHKR** [comment]
I had to remove everything, and installed via homebrew on my Mac instead of the default .pkg from Node's site. Worked after that. Maybe this will be helpful for others. Cheers!
