### ISSUE TITLE
Got this error with archiver

### ISSUE THREAD

**Issue by meetdilip** [npm/npm#12073]
I am trying to use Ionic Framework in Ubuntu 14.04. When I start a new Ionic Project, it says

> module.js:341
>     throw err;
>     ^
> 
> Error: Cannot find module 'archiver'

I was suggested to try the following and got stuck with this message when I tried to install archiver

> $ sudo npm install -g archiver﻿
> npm ERR! Linux 3.13.0-83-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "archiver﻿"
> npm ERR! node v5.9.1
> npm ERR! npm  v3.7.3
> 
> npm ERR! The header content contains invalid characters
> npm ERR! 
> npm ERR! If you need help, you may report this error at:
> npm ERR!     https://github.com/npm/npm/issues

Help please

**Comment by zkat** [comment]
Could you post your `npm-debug.log`?

**Comment by meetdilip** [comment]
Where can I find it @zkat  ?

**Comment by zkat** [comment]
It should be in the same directory where you ran npm, immediately after a failure (if you reran npm, you'll need to run the failing command again)

**Comment by meetdilip** [comment]
When I tried this 

>ionic start myApp1 blank
module.js:341
    throw err;
    ^

> Error: Cannot find module 'archiver'
>     at Function.Module._resolveFilename (module.js:339:15)
>     at Function.Module._load (module.js:290:25)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:16:19)
>     at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/utils.js:3:16)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Module.require (module.js:367:17)
> 

npm-debug.log says

> 
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', '-g', 'archiver﻿' ]
> 2 info using npm@3.7.3
> 3 info using node@v5.9.1
> 4 silly loadCurrentTree Starting
> 5 silly install loadCurrentTree
> 6 silly install readGlobalPackageData
> 7 silly fetchPackageMetaData archiver
> 8 silly fetchNamedPackageData archiver
> 9 silly mapToRegistry name archiver
> 10 silly mapToRegistry using default registry
> 11 silly mapToRegistry registry https://registry.npmjs.org/
> 12 silly mapToRegistry uri https://registry.npmjs.org/archiver
> 13 verbose request uri https://registry.npmjs.org/archiver
> 14 verbose request no auth needed
> 15 info attempt registry request try #1 at 5:46:44 AM
> 16 verbose request id 7e8a4463979020b2
> 17 http request GET https://registry.npmjs.org/archiver
> 18 verbose stack TypeError: The header content contains invalid characters
> 18 verbose stack     at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
> 18 verbose stack     at new ClientRequest (_http_client.js:85:14)
> 18 verbose stack     at Object.exports.request (http.js:31:10)
> 18 verbose stack     at Object.exports.request (https.js:196:15)
> 18 verbose stack     at Request.start (/usr/lib/node_modules/npm/node_modules/request/request.js:747:30)
> 18 verbose stack     at Request.end (/usr/lib/node_modules/npm/node_modules/request/request.js:1381:10)
> 18 verbose stack     at end (/usr/lib/node_modules/npm/node_modules/request/request.js:575:14)
> 18 verbose stack     at Immediate._onImmediate (/usr/lib/node_modules/npm/node_modules/request/request.js:589:7)
> 18 verbose stack     at tryOnImmediate (timers.js:534:15)
> 18 verbose stack     at processImmediate [as _immediateCallback] (timers.js:514:5)
> 19 verbose cwd /home/dna
> 20 error Linux 3.13.0-83-generic
> 21 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "archiver﻿"
> 22 error node v5.9.1
> 23 error npm  v3.7.3
> 24 error The header content contains invalid characters
> 25 error If you need help, you may report this error at:
> 25 error     <https://github.com/npm/npm/issues>
> 26 verbose exit [ 1, true ]

**Comment by zkat** [comment]
can you install anything else? This is a strange error (and I'm not seeing it).

Also, it's very likely you want to install archiver locally, so `npm install archiver` without the `-g` inside your ionic project.

**Comment by meetdilip** [comment]
Thanks @zkat . I got this when I tried sudo npm install archiver. Still unable to start any Ionic project

> $ sudo npm install archiver
> 
> /home/dna
> `-- archiver@0.21.0 
> 
> npm WARN enoent ENOENT: no such file or directory, open '/home/dna/package.json'
> npm WARN dna No description
> npm WARN dna No repository field.
> npm WARN dna No README data
> npm WARN dna No license field.


PS : I installed Corebird a couple of days back. I have tried a few other dependencies like bower some 3-4 hours back. 

What to do ?

**Comment by zkat** [comment]
Honestly, this is more of an ionic issue -- please make sure you followed their instructions properly, and that they've encoded any relevant dependencies.

They probably have a getting started guide that will walk you through the necessary steps.

**Comment by KenanY** [comment]
Closing since this is not an issue with `npm` itself.
