### ISSUE TITLE
Can't use third-party modules in uninstall hook

### ISSUE THREAD

**Issue by archerrr** [npm/npm#11894]
Hey guys,

I can't find anything in issues or changelog. It worked with Node 0.12 (npm 2.14.9) but fails with 4 and 5 (npm 3.7.3).

In 4+ third-party modules are uninstalled before running uninstall hook making it impossible to require them in uninstall script.
Not being able to require modules makes it complicated to clean stuff on uninstall.

Is it a new feature or a bug or is there a new better way to do cleaning?

uninstall.js

```js 
var chalk = require('chalk')
console.log(chalk.green('done'))
```

package.json

```
{
  "uninstall": "node uninstall.js"
}
```

```
nvm use 0.12
npm link
npm rm
...
done
```

```
nvm use 5
npm link
npm rm
...
> node uninstall.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'chalk'
...
```

**Comment by zkat** [comment]
It's little surprise that we had some lifecycle-related changes after `npm@3` got launched, since a lot of that stuff was actually underspecified.

It's possible that `preuninstall` might help you here, but this part of the installer is a fairly involved bit of code to suss out. What you are seeing is not the intended behavior, and this is definitely a bug. Nice catch, and thanks for reporting it! :tada:

**Comment by iarna** [comment]
I tried this and I can't reproduce it in 3.7.3 or 3.8.1:
```
$ mkdir a
$ cat > a/package.json
{
  "name": "a",
  "version": "1.0.0",
  "scripts": {
    "uninstall": "node uninstall.js"
  },
  "dependencies": {
    "chalk": "*"
  }
}
^D
$ cat > a/uninstall.js
var chalk = require('chalk')
console.log(chalk.green('done'))
^D
$ mkdir node_modules
$ npm install a
/Users/rebecca/code/npmtest/uninstall
└─┬ a@1.0.0
  └─┬ chalk@1.1.1
    ├─┬ ansi-styles@2.2.0
    │ └── color-convert@1.0.0
    ├── escape-string-regexp@1.0.5
    ├─┬ has-ansi@2.0.0
    │ └── ansi-regex@2.0.0
    ├── strip-ansi@3.0.1
    └── supports-color@2.0.0
$ npm uninstall a

> a@1.0.0 uninstall /Users/rebecca/code/npmtest/uninstall/node_modules/a
> node uninstall.js

done
- a@1.0.0 node_modules/a
- ansi-regex@2.0.0 node_modules/ansi-regex
- ansi-styles@2.2.0 node_modules/ansi-styles
- chalk@1.1.1 node_modules/chalk
- color-convert@1.0.0 node_modules/color-convert
- escape-string-regexp@1.0.5 node_modules/escape-string-regexp
- has-ansi@2.0.0 node_modules/has-ansi
- strip-ansi@3.0.1 node_modules/strip-ansi
- supports-color@2.0.0 node_modules/supports-color
```

**Comment by archerrr** [comment]
Thank you very much for the feedback.
That's weird using your code I'm able to reproduce (I've installed Node using `nvm`) and I'm on OS X El Capitan (10.11.3).

```sh
~ $ mkdir uninstall
~ $ cd uninstall/
~/uninstall $ npm -v
3.7.3
~/uninstall $ node -v
v5.8.0
~/uninstall $ mkdir a
~/uninstall $ cat > a/package.json
{
  "name": "a",
  "version": "1.0.0",
  "scripts": {
    "uninstall": "node uninstall.js"
  },
  "dependencies": {
    "chalk": "*"
  }
}
^C                               
~/uninstall $ cat > a/uninstall.js
var chalk = require('chalk')
console.log(chalk.green('done'))
^C
~/uninstall $ mkdir node_modules
~/uninstall $ npm install a
/Users/aaron/uninstall
└─┬ a@1.0.0 
  └─┬ chalk@1.1.1 
    ├─┬ ansi-styles@2.2.0 
    │ └── color-convert@1.0.0 
    ├── escape-string-regexp@1.0.5 
    ├─┬ has-ansi@2.0.0 
    │ └── ansi-regex@2.0.0 
    ├── strip-ansi@3.0.1 
    └── supports-color@2.0.0 

npm WARN enoent ENOENT: no such file or directory, open '/Users/aaron/uninstall/package.json'
npm WARN uninstall No description
npm WARN uninstall No repository field.
npm WARN uninstall No README data
npm WARN uninstall No license field.
~/uninstall $ npm uninstall a

> a@1.0.0 uninstall /Users/aaron/uninstall/node_modules/a
> node uninstall.js


module.js:341
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/aaron/uninstall/node_modules/a/uninstall.js:1:75)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
npm WARN lifecycle a@1.0.0~uninstall: continuing anyway a@1.0.0 uninstall: `node uninstall.js`
npm WARN lifecycle Exit status 1
- a@1.0.0 node_modules/a
- ansi-regex@2.0.0 node_modules/ansi-regex
- ansi-styles@2.2.0 node_modules/ansi-styles
- chalk@1.1.1 node_modules/chalk
- color-convert@1.0.0 node_modules/color-convert
- escape-string-regexp@1.0.5 node_modules/escape-string-regexp
- has-ansi@2.0.0 node_modules/has-ansi
- strip-ansi@3.0.1 node_modules/strip-ansi
- supports-color@2.0.0 node_modules/supports-color
npm WARN enoent ENOENT: no such file or directory, open '/Users/aaron/uninstall/package.json'
npm WARN uninstall No description
npm WARN uninstall No repository field.
npm WARN uninstall No README data
npm WARN uninstall No license field.
~/uninstall $ 
```

Do you want me to try something else?

I've also tried to read `node_modules`when uninstalling:

```sh
~/uninstall $ npm install a
~/uninstall $ cat > node_modules/a/uninstall.js 
console.log(require('fs').readdirSync(__dirname + '/..'))
^C
~/uninstall $ npm uninstall a

> a@1.0.0 uninstall /Users/aaron/uninstall/node_modules/a
> node uninstall.js

[ '.staging', 'a' ]
- a@1.0.0 node_modules/a
- ansi-regex@2.0.0 node_modules/ansi-regex
- ansi-styles@2.2.0 node_modules/ansi-styles
- chalk@1.1.1 node_modules/chalk
- color-convert@1.0.0 node_modules/color-convert
- escape-string-regexp@1.0.5 node_modules/escape-string-regexp
- has-ansi@2.0.0 node_modules/has-ansi
- strip-ansi@3.0.1 node_modules/strip-ansi
- supports-color@2.0.0 node_modules/supports-color
npm WARN enoent ENOENT: no such file or directory, open '/Users/aaron/uninstall/package.json'
npm WARN uninstall No description
npm WARN uninstall No repository field.
npm WARN uninstall No README data
npm WARN uninstall No license field.
```

**Comment by NotMyself** [comment]
Here is a repository with a repro of this bug: https://github.com/NotMyself/ghost-azurestorage

Note that `preuninstall` fails because rimraf is removed before the script is called.

**Comment by all3fox** [comment]
I have also run into this issue (uninstall.js requires a module that gets uninstalled right before that)

However,  the minimum working example from @iarna did not trigger the bug for me. But in the real world the bug gets triggered. My versions:

* `npm -v` is `3.10.3`
* `node -v` is `v6.3.0`
* node/npm is setup via nvm
* OS is ArchLinux

**Comment by CedricReichenbach** [comment]
We're facing this problem too, seen on Windows and OS X, both through `npm uninstall -g`.

It seems to me there's a racing condition sometimes moving `node_modules` away before `preuninstall` hooks are run. I was able to sometimes reproduce this by adding the following snippet to the top of my preuninstall script:

```
console.log('preuninstall loaded')

// busy-wait for 20 seconds
var waitUntil = new Date(new Date().getTime() + 20000);
while (waitUntil > new Date()) {}

console.log('block released')
```

When `preuninstall loaded` was printed, `mymodule/node_modules` had *sometimes* been moved to  `.mymodule.MODULES`. This seems happen in `lib/install/remove.js` inside `removeDir`, but I don't see right now where `preuninstall` is triggered and thus where the racing condition might be.

**Comment by SamVerschueren** [comment]
Because I was affected by this, and apparently this is already a problem for more then 1 year, I created a repository that illustrates the problem.

https://github.com/SamVerschueren/npm-iss11894

1. `npm install -g npm-iss11894`
2. You can now see the files that are installed (`ls` is being executed in `postinstall`)
3. `npm uninstall -g npm-iss11894`
4. `ls` is being executed again as `preuninstall` but `node_modules` are missing

<img width="752" alt="screen shot 2017-05-23 at 21 47 13" src="https://cloud.githubusercontent.com/assets/1913805/26373509/139949b6-4002-11e7-801b-dab0d9d3957d.png">

**npm**: v3.10.8
**node**: 6.9.1

**Comment by chrisui** [comment]
`husky` is itself an example of this. install it as a dep or try running it on ci with latest node/npm and you get "unable to find module". See https://github.com/typicode/husky/issues/109#issuecomment-307376287
