### ISSUE TITLE
Error after Update 'Cannot find module json-schema'

### ISSUE THREAD

**Issue by bJohnny** [npm/npm#14566]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?
running `npm` in any directory causes error: cannot find module 'json-schema'

#### How can the CLI team reproduce the problem?
After updating Node.js to v6.9 following [this instruction](http://bit.ly/2ejCoXl) i still got the error. Even after removing Node completeley and re-install it.

[Gist: output of npm](https://gist.github.com/bJohnny/d888d6b36e268c5ec954d299796251b4)

### supporting information:
 - `npm -v` prints: `3.8.10`

 - `node -v` prints: `v6.9.1`
 - `npm config get registry` prints: the same error as above
 - OS: Windows_NT 10.0.14393

**Comment by legodude17** [comment]
Have you tried reinstalling `npm`?

**Comment by KenanY** [comment]
Closing due to lack of response.
