### ISSUE TITLE
Installing node.js get error - after npm install - cannot find module internal/util/types (Windows 10 64bit)

### ISSUE THREAD

**Issue by antrez770** [npm/npm#19032]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by antrez770** [comment]
Installing node.js get error - after npm install - cannot find module internal/util/types (Windows 10 64bit)

**Comment by disophisis** [comment]
Seeing this as well on a Windows 10 Pro machine.

npm -v: 5.5.1
node -v: 8.9.0

Was also seeing this on 8.8.1 and after a fresh install of node 8.9.0 I'm still seeing it.

stacktrace from log file:

> 5 verbose stack Error: Cannot find module 'internal/util/types'
5 verbose stack     at Function.Module._resolveFilename (module.js:536:15)
5 verbose stack     at Function.Module._load (module.js:466:25)
5 verbose stack     at Module.require (module.js:579:17)
5 verbose stack     at require (internal/module.js:11:18)
5 verbose stack     at evalmachine.<anonymous>:31:26
5 verbose stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\cmd-shim\node_modules\graceful-fs\fs.js:11:1)
5 verbose stack     at Module._compile (module.js:635:30)
5 verbose stack     at Object.Module._extensions..js (module.js:646:10)
5 verbose stack     at Module.load (module.js:554:32)
5 verbose stack     at tryModuleLoad (module.js:497:12)
5 verbose stack     at Function.Module._load (module.js:489:3)
5 verbose stack     at Module.require (module.js:579:17)
5 verbose stack     at require (internal/module.js:11:18)
5 verbose stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\cmd-shim\node_modules\graceful-fs\graceful-fs.js:3:27)
5 verbose stack     at Module._compile (module.js:635:30)
5 verbose stack     at Object.Module._extensions..js (module.js:646:10)

**Comment by antrez770** [comment]
Is the solution is exist? Because on windows 7 it is working very well
Or can I install it on MAC?

**Comment by disophisis** [comment]
I found a fix for myself.  Uninstalling node and deleting the node directory from C:\Program Files and then reinstalling node appears to have taken care of this.  It looks like the uninstall process is leaving some junk behind that is causing issues.

**Comment by antrez770** [comment]
I did it twice but it is not working, can You write Your solution step by step please?

**Comment by campbellgoe** [comment]
Same issue on Windows 10 Home after upgrading from 6.? to 8.9.0

**Comment by antrez770** [comment]
What is the solution You got? 
received the same err:
npm err windows_nt 10.0.10240
npm err argv "c:\\Program Files\node.js\\node.exe" "c:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\npm-cli.js" "i" "npm" "-g"
npm err v8.9.0
npm err v3.3.12 
npm err code MODULE_NOT_FOUND
cannot find module 'internal/util/types'

**Comment by campbellgoe** [comment]
you have Programm Files instead of Program Files change your env var
also username should be your actual username

mine:
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\George\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm@latest" "-g"
npm ERR! node v8.9.0
npm ERR! npm  v3.5.3
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/util/types'

**Comment by antrez770** [comment]
Fixed  it were written just on this issue, so is not the problem, but how can I get the env var?

**Comment by campbellgoe** [comment]
search windows for advanced system settings and then choose it and you see a window with 'environmental variables' and you can make sure PATH and NODE_PATH are correct.

**Comment by antrez770** [comment]
node_path variable not exist

**Comment by campbellgoe** [comment]
Fixed for me, solution:
Uninstall node.js and completely delete npm and npm-cache from AppData.
https://www.ghacks.net/2017/07/18/how-to-delete-large-folders-in-windows-super-fast/
Remove all node.js and npm from Environmental Variables
Install node.js (8.9.0)
Follow this:
https://github.com/felixrieseberg/npm-windows-upgrade
to upgrade npm to 5.5.1 on windows easily.

**Comment by ndenton** [comment]
This worked for me. Upgrade to 8.9.0 left npm 3.5.1 in place. I didn't have to install the npm-windows-upgrade after deleting the npm and npm-cache as it turns out, but I did anyhow as it's a great utility.

**Comment by antrez770** [comment]
ndenton I have node 8.9.0 npm 3.5.1 I can't update. and it is not working for me(

**Comment by wangjingithub** [comment]
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\
bin\\npm-cli.js" "install" "-g" "nrm"
npm ERR! node v8.9.0
npm ERR! npm  v3.5.3
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/util/types'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\Desktop\firstVue\npm-debug.log


help me!please

**Comment by antrez770** [comment]
I installed on virtual machine Ubuntu, nodejs and npm and received the following error:
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at requireDir (/home/user/Downloads/path/node_modules/require-dir/index.js:116:33)
    at Object.<anonymous> (/home/user/Downloads/path/gulpfile.js:5:1)
    at Module._compile (module.js:410:26)

After these steps from this page - https://github.com/ExLibrisGroup/primo-explore-devenv 
Would have anybody Instruction like this for Linux (Ubuntu)?

**Comment by antrez770** [comment]
Hi GCDeveloper I tried do what You adviced to me, but it is not working, and the System variables PATH exist - C:\Users\user\AppData\Roaming\npm and NODE_PATH don't exist can it be the reason for any mistake? and the installation code of the scripts in c:\path

**Comment by antrez770** [comment]
If somebody will have working solution please write here step by step.

**Comment by almothafar** [comment]
Have you tried solution here https://stackoverflow.com/a/40406482/765965

**Comment by antrez770** [comment]
Hi Almothafar, my problems starts when I do - "npm install npm@3.3.12 -g"

**Comment by galtadmor** [comment]
Same here.

I upgraded from Node 6.9.0 to 8.9.0, because of our new Angular (5) project. But... that caused our old AngularJS project to not work. Running gulp (with webpack-dev-server) on the old project just failed to initialize.
I tried uninstalling and installing again and again - different versions, cleaning the app-data folder, etc... Nothing seemed to work, but simply reverting to 6.9.0. Fortunately, my new project still works with it, so no harm is done.

That's obviously not a solution. If anyone has a better suggestion - please let us know 🙃

**Comment by antrez770** [comment]
Hi Galtadmor, what Operation Systems do You use?
Please write me the version and how install what working on Your PC now. I Should start and no matter what version it will be, it should start working.

**Comment by galtadmor** [comment]
@antrez770 
I use Windows 10 64Bit. Before today, I had 6.9.0, and after upgrading to 8.9.0, gulp tasks failed to work. The error was: "internal/util/types", exactly like the author of this post typed.

**Comment by galtadmor** [comment]
@antrez770 
I use Windows 10 64Bit. I used to work with v6.9.0 of NodeJS, but since I upgraded my new project from Angular 4 to 5, I wanted to also upgrade my NodeJS to the latest stable version (8.9.0). Wasn't the smartest move 😄 
It's a relatively new issue, and I couldn't find a good answer online, so I just reverted back to 6.9.0:
https://nodejs.org/download/release/v6.9.0/
Now both projects (AngularJS + gulp + webpack, and Angular + Angular-CLI) work properly.

**Comment by antrez770** [comment]
Thank You very much for Your reply Galtadmor, I see many links of this version please tell me what is Your?

**Comment by galtadmor** [comment]
node-v6.9.0-x64.msi
https://nodejs.org/download/release/v6.9.0/node-v6.9.0-x64.msi

**Comment by athe0i** [comment]
hello guys. just had the same problem with bower. node 8.9.0 + npm 5.5.1. update did help, soo... try to update npm, think that should work.

**Comment by galtadmor** [comment]
Node 8.9.0 includes NPM 5.5.1 right off the bat, so by uninstalling your old Node, deleting Roaming data, and installing 8.9.0 - it should solve itself out. I don't think there's a reason to re-update your NPM, as you should have version 5.5.1 anyway. Unfortunately, I don't believe that this is the solution.

**Comment by fluentd** [comment]
Running into the same problem as well.Is it possible to downgrade Node in just a single folder? I have other projects that rely on my current version 8.8.1 of Node and NPM.

**Comment by campbellgoe** [comment]
use Node Version Manager nvm

**Comment by GaborSzalay** [comment]
Same issue here, win10 enterprise x64, node 8.9.0 and npm 5.5.1 appeared this error.
After installing an [nvm 1.1.5](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.5) and downgrading my node to 6.9.0 and my npm to 3.10.8 I was able to successfully build the same project.
Looking forward to see this issue fixed on higher versions.

**Comment by YaqiLee** [comment]
Remove folders  "C:\Users\lyqhn\AppData\Roaming\npm\node_modules\npm and run "npm install -g npm"

**Comment by WaleedAshraf** [comment]
Still facing same issue on mac.
node@8.9.1 and npm@5.5.1

**Comment by erdemalpay** [comment]
I'm still facing too on ubuntu.
node@8.9.1 and npm@5.5.1
Reinstalling node-npm didn't work.

**Comment by xkons** [comment]
Same here on Ubuntu 14.04.5
Deleting the node_modules folder and generating a new package-lock.json fixed it for me last week but since yesterday that won't help either.
node@8.9.1 and npm@5.5.1

**Comment by WaleedAshraf** [comment]
Fixed!
If any of your dependency or peer dependency is using graceful-fs < 4.x , you need to upgrade it to latest version graceful-fs@4.1.11

**Comment by outluch** [comment]
I dont get, what should i do? 
```
mkdir tt & cd tt
npm init -y
npm i moment
```
returns same error. Which dependency should I upgrade?
```
➜  tt node -v
v9.2.0
➜  tt npm -v
5.5.1
```

SOLVED:
downgraded node to 6.9.1 + npm to 3.* (dont remember) (via n node version changer)
then `npm i -g npm@latest`
then upgraded node to 9.2.0 and npm is working now.

**Comment by jartaud** [comment]
Thanks @YaqiLee deleting `C:\Users\me\AppData\Roaming\npm` works for me.

**Comment by radoslavpetranov** [comment]
Windows 8.1 machine. Upgraded from Node 6.11 to node 8.9.1. Resolved by removing `C:\Users\me\AppData\Roaming\npm`.

Please fix this in the installation - issues like this should not be part of a stable release.

**Comment by gladwinput** [comment]
On Windows:
I upgraded to 9.2.0, encountered this issue. Then deleted C:\Users\%USER%\AppData\Roaming\npm

Then ran the repair in the install and this resolved the problem.

**Comment by antrez770** [comment]
Hi gladwinput write please version of Windows and link to node packet 9.2.0.
Also if there somebody who did it too, please write about.

**Comment by gladwinput** [comment]
latest version from node site, direct link:
https://nodejs.org/dist/v9.2.0/node-v9.2.0-x64.msi

Windows 10 64bit

**Comment by et304383** [comment]
Why is this still broken in 8.9.1 LTS?

**Comment by lgg** [comment]
@almothafar's link helped me! (https://stackoverflow.com/questions/40308623/cannot-find-module-internal-fs-afer-upgrading-to-node-7/40406482#40406482)

win7

**Comment by almothafar** [comment]
I don't see why some prefer to remove all npm modules globally and reinstall it and waste the time, it is mostly a cache issue, only do it if you just really gave up all solutions, I provided a solution for Windows and Linux here https://stackoverflow.com/a/40406482/765965 and some provided solution for MacOS.

In simple words, remove `C:\Users\<USER-NAME>\AppData\Roaming\npm-cache` for windows and you maybe need to fix permission for Linux and MacOS, for your project remove `node_modules` and `npm i` again.

Finally, I think `yarn` is really good option to have to save you from a lot of headaches.

**Comment by boaldave** [comment]
Uninstall node.js, completely delete npm and npm-cache from AppData/Roaming, reinstall Node 8.9.3, worked for me. Windows 10 Pro 64. Now:
   node -v = 8.9.3
   npm -v = 5.5.1
After global install of angular/cli
   ng -v = 1.6.1

**Comment by ghost** [comment]
Please implement step by step as following.
- $npm cache clean
- Delete npm folder in your local folder
- uninstall node.js.

**Comment by lexspoon** [comment]
I ran into this error message. Reinstalling node did not help. However, removing `node_modules` did get my system to recover.

Apparently `npm install` does not always remove or upgrade garbage that is in the `node_modules` directory. So, that directory can get into a bad state without `npm` realizing it.

**Comment by GaborSzalay** [comment]
Just got another final laptop instead of the temporary one and I had to reinstall everything from scratch. Instead of downgrading my node version  [as I wrote here](#issuecomment-342545165), I took @almothafar 's advice. Deleting node cache didn't help - tried it twice -, but [installing yarn](https://yarnpkg.com/en/docs/install) solved my problem, I could install the deps via yarn. Thanks for that!

**Comment by robson-hennes** [comment]
Thanks disophisis !

**Comment by CoryDanielson** [comment]
Had this same issue, was able to fix it by uninstalling node, then deleting C:\Users\<MyUser>\AppData\Roaming\npm and npm-cache. Once I reinstalled node after that, it was fine.

AppData is a hidden folder so you'll have to display those.

**Comment by dorothyDorothy** [comment]
I found that I can use npm version 9.0.0 but I had to uninstall gulp-sass and then reinstall it.  All was fine after that

**Comment by chr4ss1** [comment]
Forget it.

the only correct solution there is:

Rm -rf every single instance of NPM you can find in your computer, and then manually download new NPM from nodejs.org

**Comment by zhulin2609** [comment]
maybe you have multiple versions graceful-fs
1. `npm list graceful-fs`
2. rm invalid's graceful-fs
3. `npm install`

**Comment by sharanbm** [comment]
Delete npm and npm-cache directories from AppData\Roaming directory on windows if you are facing this problem. 

it worked for me.

**Comment by mmfilesi** [comment]
Some isue with node v10.1.0

**Comment by langald** [comment]
This helped to me Windows 8.1 x64:
1 Uninstalling node,
2 Deleting folder nodejs from Program Files
3 Deleting C:\Users<MyUser>\AppData\Roaming\npm and npm-cache. 
4 Reinstalling node

**Comment by rhovell** [comment]
Hi I've just updated node.js to try and fix this bug with no prevail. Any ideas?

$ npm -v
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at evalmachine.<anonymous>:44:26
    at Object.<anonymous> (C:\Users\rhove\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)

Thanks
