### ISSUE TITLE
"undefined is not a function" with iojs 1.5.1/npm 2.7.0 (Linux)

### ISSUE THREAD

**Issue by mscdex** [npm/npm#7635]
Steps to reproduce:

* Create `package.json`:
```javascript
{
  "dependencies": {
    "socksv5": "git+https://github.com/mscdex/socksv5.git"
  }
}
```
* Then within same directory: `npm install`

It *does* work with node v0.10.30/npm 1.4.21

**Comment by mscdex** [comment]
[`npm-debug.log`](https://gist.github.com/mscdex/a3f82cdc679c57ed6b57)

**Comment by KenanY** [comment]
@mscdex I believe https://github.com/mscdex/socksv5/pull/5 will fix your issue. `bundledDependencies` should be an array, not a hash https://docs.npmjs.com/files/package.json#bundleddependencies

Works for me:

``` json
{
  "dependencies": {
    "socksv5": "git+https://github.com/KenanY/socksv5.git#bundled-array"
  }
}
```

**Comment by mscdex** [comment]
You're right, my mistake. However, there should be a better error message than that...

**Comment by KenanY** [comment]
@mscdex I agree. I'm sure all that's needed is an `isArray` check somewhere. Maybe I'll take a look tomorrow.

**Comment by KenanY** [comment]
Relevant: so apparently there's a warning for this kind of thing; it is [emitted](https://github.com/npm/normalize-package-data/blob/b73bbb7fe07414f25caf92f7a49509688e7a89e4/test/dependencies.js#L28) by [`npm/normalize-package-data`](https://github.com/npm/normalize-package-data) when one runs `npm install` in a package whose `bundledDependencies` is not an _Array_. Error message can still be better  though.

**Comment by KenanY** [comment]
Fixed in [`npm@2.7.4`](https://github.com/npm/npm/releases/tag/v2.7.4) :)

```
$ npm i mscdex/socksv5#0d0acea
npm ERR! Linux 3.18.6-1-ARCH
npm ERR! argv "/home/kenan/local/bin/iojs" "/home/kenan/.npm-packages/bin/npm" "i" "mscdex/socksv5#0d0acea"
npm ERR! node v1.6.1
npm ERR! npm  v2.7.4

npm ERR! socksv5's `bundledDependencies` should be an array
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kenan/Code/npm-7635/npm-debug.log
```

**Comment by mscdex** [comment]
@KenanY :+1:

**Comment by iarna** [comment]
Closing as resolved.
