### ISSUE TITLE
Npm outdated doesn't work on v2.12.0

### ISSUE THREAD

**Issue by ingro** [npm/npm#8694]
After updating to npm v2.12.0 seems like the `outdated` command doesn't work anymore, here's the error from `npm-debug.log`:
```
verbose get saving gulp-changed to C:\Users\Emanuele\AppData\Roaming\npm-cache\registry.npmjs.org\gulp-changed\.cache.json
verbose stack TypeError: undefined is not a function
verbose stack     at calculateOwner (C:\Users\Emanuele\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:37:24)
verbose stack     at C:\Users\Emanuele\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:23:22
verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
```

I'm running on a Windows 7 x64 machine with Node 0.12.2.

**Comment by othiym23** [comment]
There's a known issue (mentioned in the [release notes](https://github.com/npm/npm/releases/v2.12.1) for `npm@2.12.1`) with `npm@2.12.0` on Windows. You might need to reinstall npm using a Node installer, but after that, if you run `npm install -g npm@next`, you'll get a version of npm that doesn't have this problem. I was fixing another bug and introduced that regression. I apologize for the inconvenience of the fix!
