### ISSUE TITLE
Getting error after running the command "npm install".

### ISSUE THREAD

**Issue by shivamshukla** [npm/npm#5542]
IN npm-debug.log, last few lines before error started....
 
```
7773 silly lockFile d89fdb6e-deep-extend-0-2-5 deep-extend@~0.2.5
7774 silly lockFile d89fdb6e-deep-extend-0-2-5 deep-extend@~0.2.5
7775 silly gunzTarPerm extractEntry test/perm_sync.js
7776 silly gunzTarPerm extractEntry test/rel.js
7777 silly gunzTarPerm extractEntry test/root.js
7778 silly gunzTarPerm extractEntry test/sync.js
7779 silly gunzTarPerm extractEntry test/umask.js
7780 silly gunzTarPerm extractEntry test/umask_sync.js
7781 error Error: EPERM, unlink 'C:\Users\Shivam\AppData\Roaming\npm-cache\inherits\2.0.1\package'
7781 error  { [Error: EPERM, unlink 'C:\Users\Shivam\AppData\Roaming\npm-cache\inherits\2.0.1\package']
7781 error   errno: 50,
7781 error   code: 'EPERM',
7781 error   path: 'C:\\Users\\Shivam\\AppData\\Roaming\\npm-cache\\inherits\\2.0.1\\package',
7781 error   parent: 'tar' }
7782 error Please try running this command again as root/Administrator.
7783 error System Windows_NT 6.1.7601
7784 error command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
7785 error cwd f:\Workspace\Angular_workspace\angular-phonecat
7786 error node -v v0.10.28
7787 error npm -v 1.4.9
7788 error path C:\Users\Shivam\AppData\Roaming\npm-cache\inherits\2.0.1\package
7789 error code EPERM
7790 error errno 50
7791 error stack Error: EPERM, unlink 'C:\Users\Shivam\AppData\Roaming\npm-cache\inherits\2.0.1\package'
7792 verbose exit [ 50, true ]
```
-------------------------------------------------------------------------------------------------------------------------------------------------------
in npm console it says
```
npm http GET https://registry.npmjs.org/binary/-/binary-0.3.0.tgz
npm ERR! Error: EPERM, unlink 'C:\Users\Shivam\AppData\Roaming\npm-cache\inherit
s\2.0.1\package'
npm ERR!  { [Error: EPERM, unlink 'C:\Users\Shivam\AppData\Roaming\npm-cache\inh
erits\2.0.1\package']
npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\\Users\\Shivam\\AppData\\Roaming\\npm-cache\\inherits\\2.0.
1\\package',
npm ERR!   parent: 'tar' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodej
s\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd f:\Workspace\Angular_workspace\angular-phonecat
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! path C:\Users\Shivam\AppData\Roaming\npm-cache\inherits\2.0.1\package
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, unlink 'C:\Users\Shivam\AppData\Roaming\npm-cache\i
nherits\2.0.1\package'
npm http 200 https://registry.npmjs.org/qs
```

**Comment by demaniak** [comment]
Ok, strange. Had pretty much the same issues (tried running from gitbash and windows powershell - same results).
After changing cache folder...things started working (could use yo to generate angular app, without errors). 
The weird thing is, I could not see that the specified cache location was ever actually used (no files were put there).

**Comment by vdecree** [comment]
I can confirm things seemed to start to work by changing cache location. On Windows 8 here too..

**Comment by attebury** [comment]
Changing the cache location on Windows 7 worked for me too.

**Comment by larshaupthansen** [comment]
Changing the cache location on Windows 10 build 10074 didn't work (had no problems on Windows 8.1)

**Comment by larshaupthansen** [comment]
I solved the issue by updating npm to version 2.10.1 (using https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)

**Comment by brendat481** [comment]
Changing the cache location on Windows 8.1 worked for me too.

**Comment by Dmmo** [comment]
npm command error when i upgrade my nodejs to v4.0.

error:
luowenlindeMacBook-Pro:~ lwl$ npm
module.js:338
    throw err;
    ^

Error: Cannot find module '../utils/correct-mkdir.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/cache/get-stat.js:2:20)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by carmelolg** [comment]
When you try to reinstall or update a package, npm try to delete this package and to reinstall it. 

But not all the directories of this package will be correctly deleted. 
So try to unistall this package manually and after run npm install.
Let me know.

**Comment by FieldMarshallVague** [comment]
Thankyou!  Changing cache folder worked for me on Windows 10.

Copying it again here so people don't hunt for it in comment list:

npm config set cache C:\Dev\nodejs\npm-cache --global

**Comment by Wikibeast** [comment]
Changing the cache worked for me on Windows 10 as well, thank you.

**Comment by amitsaroj001** [comment]
changing the cache path work for me too on windows 10 thnks!!!

**Comment by samuelmichaud** [comment]
+1 for `npm config set cache C:\Dev\nodejs\npm-cache --global` patch worked for me on windows 10

**Comment by emb0624** [comment]
@samuelmichaud solution works for me on Win 10. Thanks!

**Comment by diesire** [comment]
For me, on Windows 7 with node `v5.1.0` and  npm `v3.5.0` everything failed except shutting down the antivirus (McAfee). I didn't need to change the cache

**Comment by CharlJKruger** [comment]
`npm config set cache C:\Dev\nodejs\npm-cache --global` also resolved the issue on windows 10, thank you!

**Comment by MaxPleaner** [comment]
there is clearly a solution for windows users but none for unix...

**Comment by kucherenkovova** [comment]
Had the same issue, turning off windows defender worked for me

**Comment by kmanion** [comment]
Hi @shivamshukla, it looks like you've gotten some help with this issue. We're trying to close out some of the older support issues. Please don't hesitate to reopen if you are still running into this or email us at support@npmjs.com

Kiera, npm technical support

**Comment by rnimmada** [comment]
Hi guys i am trying to upgrade my Api connect version to 5.0.3 while  i am trying to creating data source by using command line with create --type datasource command but i am getting the following error

lob error { [Error: EPERM: operation not permitted, scandir 'C:\Users\miracle\A
plication Data']
 errno: -4048,
 code: 'EPERM',
 syscall: 'scandir',
 please any one from the team pls give the solution for this

**Comment by VishalGulati** [comment]
Hi I am also facing the issue on deploying angular2 app on Azure. I tried clearing cache using npm cache clean but it did not work. Since its on Azure I dont think Antivirus will be hindering anything. Please suggest a solution. My query on stackoverflow: http://stackoverflow.com/questions/40241392/package-json-fails-with-error-windows-nt-6-2-9200-on-azure?noredirect=1#comment67775269_40241392

**Comment by poodong** [comment]
![image](https://cloud.githubusercontent.com/assets/22137434/20684421/b23e8298-b614-11e6-827f-493dfad47d29.png)

I 've tried all the solutions mentioned above but none worked for me.....any suggestions???

**Comment by s2zaman** [comment]
Error parts: 
`npm ERR! Please try running this command again as root/Administrator.`
`npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\myUser\AppData\Roaming\npm-cache\`

Solution:
Just **set full write/read permissions** to the installed directory of `nodejs `and `node_modules`
For example this directory: _C:\Program Files\nodejs_

Basically i got this error on bamboo (hosted on windows OS), the user **myUser** was not permitted to perform the rename operation.
**:) all okay now**

**Comment by KingGeneral** [comment]
hi this solution for you may it work : 

> npm config set cache C:\Program Files\nodejs\npm-cache --global

see where you install your nodejs , 
copy it and type that path as cache like above code

thx

**Comment by AliNm14** [comment]
@poodong 

Did you find the solution ?

**Comment by jthomasson28** [comment]
I ran the command:
`npm config set cache C:\Dev\nodejs\npm-cache --global`
from above and it fixed the error. Thanks! I'm wondering if when installing React JS, I shouldn't run the `npm install -g create-react-app` to start a new project? That may be where the caching issue is coming from.

**Comment by tenznhok** [comment]
I have the same problem when I run npm install
