### ISSUE TITLE
npm semver BUG

### ISSUE THREAD

**Issue by teheavy** [npm/npm#11872]
NodeJs was working before (version 0.2.XX), but after I updated my node.js to 4.4.0 and 4.3.2 on my windows 10 machine and try to run npm --version, it shows:

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Fred\AppData\Roaming\npm\node_modules\npm\lib\config\defaults.js:6:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

I've tried to updated my environmental path and reinstalled an earlier version of NodeJs, but all of the recent releases didn't solve the issue.

**Comment by zkat** [comment]
Hi! Please [remove node entirely from windows](http://stackoverflow.com/a/20711410) and try to install with a [freshly-downloaded `.msi` from the nodejs site](https://nodejs.org/en/).

Let me know if that helps. :)

**Comment by teheavy** [comment]
Thanks! It works!

**Comment by dajasra** [comment]
I am getting the same issue all of a sudden. I am on a mac.
